### ISSUE TITLE
where is the ganache-cli repository ?

### ISSUE THREAD

**Issue by moda20** [ConsenSys-archive/ganache#1120]
I am trying to get the docs of the cli version of ganache but they keep redirecting to this repo with no docs for the cli arguments.

**Comment by davidmurdoch** [comment]
I apologize for the confusion. The documentation has moved to https://github.com/trufflesuite/ganache-cli-archive

We're combining ganache-core and ganache-cli into `ganache`, but haven't yet finished everything. I'll be sure to put a link into this REPO's README.md pointing to the archive repository until we get everything situated.

That said, the npm module `ganache@7.0.0-alpha.0` (`npm install ganache@7.0.0-alpha.0 -g` to install it globally), has decent command documentation when running `ganache --help` after installing. You can learn more about why it is an alpha release [here](https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.0).
