### ISSUE TITLE
"ganache-core@2.13.1" is missing a bundled dependency "keccak"

### ISSUE THREAD

**Issue by aspiers** [ConsenSys-archive/ganache#1128]
I'm seeing the following warning when running `yarn install`:

    warning "ganache-core@2.13.1" is missing a bundled dependency "keccak". This should be reported to the package maintainer.

and I couldn't find any other mention of this reported here, so I'm filing this issue.

I believe the relevant part of `yarn.lock` is as follows:

```
"@ethereum-waffle/provider@^3.4.0":
  version "3.4.0"
  resolved "https://registry.yarnpkg.com/@ethereum-waffle/provider/-/provider-3.4.0.tgz#a36a0890d4fbc230e807870c8d3b683594efef00"
  integrity sha512-QgseGzpwlzmaHXhqfdzthCGu5a6P1SBF955jQHf/rBkK1Y7gGo2ukt3rXgxgfg/O5eHqRU+r8xw5MzVyVaBscQ==
  dependencies:
    "@ethereum-waffle/ens" "^3.3.0"
    ethers "^5.0.1"
    ganache-core "^2.13.2"
    patch-package "^6.2.2"
    postinstall-postinstall "^2.1.0"
```

**Comment by cds-amal** [comment]
Thanks @aspiers, This should be resolved in [Ganache v7.0.0-alpha.1](https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1). Please let us know if you're still experiencing problems and we'll reopen.
