### ISSUE TITLE
npm i ganache is deprecated

### ISSUE THREAD

**Issue by FeatureSpitter** [ConsenSys-archive/ganache#1157]
I am being forced to use `npm i ganache-cli`.

And by visiting https://www.npmjs.com/package/ganache it shows deprecated.

Following the README instructions didn't work.

**Comment by davidmurdoch** [comment]
`ganache-cli` is still the canonical stable release. You can use `npm install ganache@alpha --global` to install the alpha release.

**Comment by davidmurdoch** [comment]
related: https://github.com/trufflesuite/ganache/issues/1120

**Comment by MicaiahReid** [comment]
@FeatureSpitter, thanks for bringing this to our attention. We have added a notice at the top of the Ganache README directing ganache-cli users to the CLI documentation.
