### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by itsdeka** [ConsenSys-archive/ganache#1204]
Hello @davidmurdoch, awesome job.
Would it be possible to publish a release for latest commit related to EIP1559?

**Comment by davidmurdoch** [comment]
Working on it! I found an issue during release testing (it crashes start up, so it's a bit of a show stopper!) that only occurs with the bundled (webpack) release and am working on a fix now.

**Comment by davidmurdoch** [comment]
Release PR: https://github.com/trufflesuite/ganache/pull/1222

**Comment by davidmurdoch** [comment]
released in ganache-7.0.0-alpha.1
