### ISSUE TITLE
Takes hundreds of GB of space

### ISSUE THREAD

**Issue by pal9000i** [ConsenSys-archive/ganache#1276]
Hello,

Running ganache-cli for my tests takes up hundreds of GB of my computer storage after a while. I am not using --db param, so shouldn't chain state only be in memory? Looks like it is saving the chain state somewhere and not clearing it out after stopping ganache.

How can i clear out this storage?

Thanks

**Comment by davidmurdoch** [comment]
What OS are you running?

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. You can open a new issue if this is still a problem and we'd be happy to investigate.
