### ISSUE TITLE
Contract deployment gets stuck on Windows 10 using Truffle v5.4.10 & Ganache CLI v6.12.2 (ganache-core: 2.13.2)

### ISSUE THREAD

**Issue by arnab-bhowmik** [ConsenSys-archive/ganache#1316]
On Windows 10, not able to deploy Smart Contracts using Truffle v5.4.10 & Ganache CLI v6.12.2. Compilation of the smart contracts go fine but the deployments gets stuck for hours without any output. Kindly refer attached screenshot. The issue is not happening on Ubuntu 18.04 for the mentionedTruffle & Ganache versions.
![Truffle_Issue](https://user-images.githubusercontent.com/66133212/136207580-1a7c6eba-0620-4ce4-b2fe-cf814060cd8d.JPG)

**Comment by fainashalts** [comment]
Hi @arnab-bhowmik thank you for bringing this up. Can you try this on the latest version of Truffle and see if the issue persists? Can you also share your Node version?

**Comment by haltman-at** [comment]
Closing this for issue maintenance.  Feel free to open a new issue if there's still a problem here.  Thanks!
