### ISSUE TITLE
address(this).balance [incorrect] vs payable(address(this)).balance [correct] not provoking errors on ganache-cli

### ISSUE THREAD

**Issue by chris-shyft** [ConsenSys-archive/ganache#1331]
Hey, curious if this should/could be addressed - 

https://ethereum.stackexchange.com/questions/78597/solidity-0-6-0-addressthis-balance-throws-error-invalid-opcode

when performing test suite commands using ganache-cli, there is no "Invalid Opcode" error thrown by "address(this).balance", while using a protocol & performing the same transaction tests does.

**Comment by chris-shyft** [comment]
tldr; "address(this).balance" should provoke an error message
"payable(address(this)).balance" should not.

**Comment by chris-shyft** [comment]
it seems to me that the geth-y implementations don't care about this semantic difference, but the nethermind-based ones do atm. I'll leave/close this if it's a reproduction error on the nethermind side :)

**Comment by davidmurdoch** [comment]
Before I dig into this further, can you try with `ganache@7.0.0-alpha.1`? You can install by running `npm uninstall ganache-cli -g && npm install ganache@alpha -g`.

**Comment by davidmurdoch** [comment]
Just FYI: geth, nethermind, ganache never see your solidity code (`address(this).balance;`); they only see the bytecode/opcodes that the solidity compiler generates. Make sure you are are always using the same version and settings of solidity when compiling.

**Comment by chris-shyft** [comment]
we can probably close this, turns out the eip1884 ( https://eips.ethereum.org/EIPS/eip-1884#selfbalance ) wasn't enabled on our POA network setup, ty for your focus @davidmurdoch

**Comment by chris-shyft** [comment]
(https://eth.wiki/roadmap/istanbul)
