### ISSUE TITLE
Error when running ganache for tezos

### ISSUE THREAD

**Issue by DavLiendoProgramming** [ConsenSys-archive/ganache#1335]
Hi everybody, I'm trying to use ganache for tezos and I'm having on this error:
 ``Ganache CLI v6.12.0-tezos.0 (ganache-core: 2.13.2-tezos.0)

Available Accounts
==================
alice 100 TEZ
  pk: edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn
  pkh: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
bob 100 TEZ
  pk: edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4
  pkh: tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6
eve 100 TEZ
  pk: edpku9qEgcyfNNDK6EpMvu5SqXDqWRLuxdMxdyH12ivTUuB1KXfGP4
  pkh: tz1MnmtP4uAcgMpeZN6JtyziXeFqqwQG6yn6
mallory 100 TEZ
  pk: edpkujwsG5JMrWVXQwmRMBoR9yJkokRbn6wy3monpQKBpnZTs1ogRR
  pkh: tz1R2oNqANNy2vZhnZBJc8iMEqW79t85Fv7L

Private Keys
==================
edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq (alice)
edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt (bob)
edsk3Sb16jcx9KrgMDsbZDmKnuN11v4AbTtPBgBSBTqYftd8Cq3i1e (eve)
edsk3W5Fz1yWK39sLY6vidmgkfmGAXh6V2JqUiri9W1pFeeYWbFbJL (mallory)

/mnt/c/Users/David Liendo/Desktop/portfolio/ligo/tezos-starter-kit/node_modules/ganache-core/lib/tezos/flextesa.js:243
          reject(new Error(stderr));
                 ^
Error: 
    at ChildProcess.onClosed (/mnt/c/Users/David Liendo/Desktop/portfolio/ligo/tezos-starter-kit/node_modules/ganache-core/lib/tezos/flextesa.js:243:18)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.``

I'm using wsl with ubuntu, I don't know exactly what to do

**Comment by fainashalts** [comment]
Hi @DavLiendoProgramming is this still an issue for you? Apologies for the delay in getting back to you.

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but feel free to file a new issue if there's still a problem here.  Thanks!
