### ISSUE TITLE
Create GitHub discussion for ganache v7 instamine explanation

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1337]
This is intended to be created as a GitHub discussion and linked (`https://trfl.io/v7-instamine`) from Ganache's `eth_getTransactionReceipt` notice.

## Living draft:

In previous versions Ganache would "instamine" transactions in a such a way that the transaction was guaranteed to be included in a block, or throw an exception, _before_ the transaction's hash was returned to the caller.

If you use an an EIP-1193 provider directly, your code probably looks similar to this:

```javascript
const txHash = await provider.send("eth_sendTransaction", [tx]);
const txReceipt = await provider.send("eth_getTransactionReceipt", [txHash]);
assert(txReceipt != null);
```

If you use a Web3 library like web3.js or ethers.js, your code probably still works, but it is now much slower! :astonished: This happens because these libraries don't listen to the `newHeads` event soon enough (TODO: verify this claim and open issues to the fixes for these and link them here) or you are using an http url (e.g., `http://localhost:8545`) instead of a websocket url (`ws://localhost:8545`) causing the provider must always poll for changes.

```javascript
const receipt = await web3.eth.sendTransaction(tx); // this may take a whole second!
assert(receipt != null);
```

To fix this, ensure you are using a websocket url
```javascript
```

But this is not how nodes behave in the wild and has been the cause of much confusion to developers new to Ethereum.

In Ganache v7 we now add the transaction to an internal transaction pool, return the transaction hash's to the caller, and _then_ process the transaction for inclusion in a block.

This change causes the previous code to fail, as the `txReceipt` will be `null`. We currently detect when a transaction receipt for a transaction that is currently in the pool is requested and log the following message with a link to this discussion:

```bash
Ganache `eth_getTransactionReceipt` notice: the transaction with hash `{hash}` has not yet been mined.
```

In order to restore the behavior

```javascript
const txHash = await provider.send("eth_sendTransaction", [tx]);
const txReceipt = await provider.send("eth_getTransactionReceipt", [txHash]);
assert(txReceipt != null);
```

Alternatively, you can restore the old way of instamining by enabling the `--miner.legacyInstamine` flag:

On the command line:

```bash
ganache --miner.legacyInstamine
```

Or programmatically:

```javascript
ganache.provider({ miner: { legacyInstamine: true } });
```

Another important side effect of this change is that EVM exceptions that occur during the execution of your transaction are now discarded! :grimacing:

In the future we hope to implement [EIP-758 Subscriptions and filter for completed transactions](https://eips.ethereum.org/EIPS/eip-758) in Ganache and other nodes, but in the meantime you'll have to work around this problem in other ways:

...

**Comment by diwu1989** [comment]
With `legacyInstamine=False` I'm still hitting error when running:
```
            const copyTxHash = await web3ToUse.eth.personal.sendTransaction(copyTransaction(tx), '')
            console.info(`original tx hash ${txHash} fork hash ${copyTxHash}`)
            // var forkedTx = await web3ToUse.eth.getTransactionReceipt(copyTxHash)
            const forkedTx = await ganacheProvider.send('eth_getTransactionReceipt', [copyTxHash])
            if (forkedTx) {
                console.info(`forked tx in ${Date.now() - start}ms:\n${JSON.stringify(forkedTx)}`)
            } else {
                console.error(`failed to fork tx ${txHash} forked tx ${copyTxHash}`)
            }
```
I'm getting error
```
2021-12-08T17:34:37.110 app[2c983148] sjc [info] ganache log:  > Ganache `eth_getTransactionReceipt` notice: the transaction with hash
2021-12-08T17:34:37.110 app[2c983148] sjc [info]  > `0x5501c7a5304514f648d8014592c9e631418062b1e92bb9055cbcd4d8add8cf81` has not
2021-12-08T17:34:37.110 app[2c983148] sjc [info]  > yet been mined. See https://trfl.io/v7-instamine for additional information.
```

**Comment by caffeinum** [comment]
> On the command line:
> 
> ```ganache --chain.legacyInstamine```

@davidmurdoch 

This seems to be replaced by
```bash
ganache --miner.legacyInstamine
```

**Comment by davidmurdoch** [comment]
@caffeinum ah, thank you. Fixed!
