### ISSUE TITLE
'Method eth_signTransaction not supported.

### ISSUE THREAD

**Issue by LucasColas** [ConsenSys-archive/ganache#1346]
Hello,

When I try to do a transaction I have an error.
My code : 
```
nonce = web3.eth.getTransactionCount(account_1_addr)
#This methode Returns the number of transactions that
#have been sent from account

#Build a transaction
tx = {
    'nonce':nonce,
    'to':account_2_addr,
    'value':web3.toWei(1, 'ether'),
    'gas': 2000000,
    'gasPrice': web3.toWei('50', 'gwei'),
}

signed_tx = web3.eth.signTransaction(tx, account_1_PKey)

tx_hash = web3.eth.sendRawTransaction(signed_tx.rawTransaction)
print(tx_hash)
```

My error : 

> signed_tx = web3.eth.signTransaction(tx, account_1_PKey)
>   File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\module.py", line 60, in caller
>     null_result_formatters)
>   File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 190, in request_blocking
>     null_result_formatters)
>   File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 168, in formatted_response
>     raise ValueError(response["error"])
> ValueError: {'message': 'Method eth_signTransaction not supported.', 'code': -32000, 'data': {'stack': 'Error: Method eth_signTransaction not supported.\n    at GethApiDouble.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\subproviders\\geth_api_double.js:70:16)\n    at next (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:136:18)\n    at GethDefaults.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\subproviders\\gethdefaults.js:15:12)\n    at next (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:136:18)\n    at SubscriptionSubprovider.FilterSubprovider.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\subproviders\\filters.js:89:7)\n    at SubscriptionSubprovider.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\subproviders\\subscriptions.js:137:49)\n    at next (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:136:18)\n    at DelayedBlockFilter.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\subproviders\\delayedblockfilter.js:31:3)\n    at next (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:136:18)\n    at RequestFunnel.handleRequest (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\subproviders\\requestfunnel.js:32:12)\n    at next (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:136:18)\n    at Web3ProviderEngine._handleAsync (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:123:3)\n    at Timeout._onTimeout (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:107:12)\n    at listOnTimeout (internal/timers.js:531:17)\n    at processTimers (internal/timers.js:475:7)', 'name': 'Error'}}

I know signTransaction is deprecated in favor of sign_transaction().
But I had the same error when I tried sign_transaction

**Comment by davidmurdoch** [comment]
If you are using cli, can you try `ganache@7.0.0-alpha.1`? To install it globally run `npm uninstall -g ganache-cli` then run `npm install -g ganache@alpha`.

**Comment by fainashalts** [comment]
@LucasColas thank you for bringing this issue up. `ganache@7.0.0-alpha.2` does support this method, so please give it a try! We're closing this issue for maintenance but please reach out if something else comes up!
