### ISSUE TITLE
Got negative time and broke ganache in ganache-core 2.13.2

### ISSUE THREAD

**Issue by sc0Vu** [ConsenSys-archive/ganache#1366]
Hi there,

I found an interesting bug when I tried to `evm_mine` with 2147483648 timestamp, it broke my ganache core (v2.13.2) with integer 53 bits errors.

Then I dig into source code, it turns out the timestamp was negative after doing or caculation.

https://github.com/trufflesuite/ganache/blob/ff312f6ee7f54fa8a8fdce52165fa879eb8bdb20/lib/blockchain_double.js#L1251

I saw this issue was fixed in develop branch, maybe the 3 version. Will you keep v2 updated?

Thanks.

**Comment by davidmurdoch** [comment]
You can try the fixed version by installing `ganache@7.0.0-alpha.1` today by running `npm run uninstall ganache-cli -g` followed by `npm run install ganache@alpha -g`. Let me know if this next version fixes the issue; we do not currently plan to release any updates to v2 in the future.

**Comment by fainashalts** [comment]
Hi @sc0Vu thanks for bringing up this issue. Looks like @davidmurdoch has provided steps for a fix so we're going to close this for maintenance. Please reach out if you encounter any new issues!
