### ISSUE TITLE
web3_sha3 should accept hex-encoded string

### ISSUE THREAD

**Issue by domob1812** [ConsenSys-archive/ganache#1375]
The `web3_sha3` RPC method is supposed to accept a hex-encoded string for the data to hash.  So for instance, to get the Keccak hash of `Move(string,string,string,uint256,uint256,address,uint256,address)` (for a Solidity event topic), the call should be:

    web3_sha3 ("0x4d6f766528737472696e672c737472696e672c737472696e672c75696e743235362c75696e743235362c616464726573732c75696e743235362c6164647265737329")

This call returns the expected value of `0x1241ca91bf224e988427ae79840cc9e3a02fa0579a3bd3fffc1f5c363192a873` for me with a real geth instance (version 1.10.8) as well as the old `ganache-cli` (version 6.12.2).

However, with the new `ganache` in development, I get `0xfb003308ec3db2d4f5b4afd507e20a6405153cdacffdee04022877e29465e778`.  I do get the correct result if I pass in the string directly, i.e.

    web3_sha3 ("Move(string,string,string,uint256,uint256,address,uint256,address)")

From what I can see [in the code](https://github.com/trufflesuite/ganache/blob/3b10e9f3b26eb269958f48354c808ee31ad23679/src/chains/ethereum/ethereum/tests/api/web3/web3.test.ts#L23) this is kind of "intended".  However, isn't this a bug, as `ganache` should follow the RPC spec and be consistent with the behaviour of other clients (like geth)?

**Comment by davidmurdoch** [comment]
Thanks for trying out the alpha. It should work to spec. This will be fixed before release to stable. Thank you for reporting this!
