### ISSUE TITLE
Recent v7.0.0-alpha.1 does not include proper type declaration

### ISSUE THREAD

**Issue by ukstv** [ConsenSys-archive/ganache#1412]
Using ganache from TypeScript code. Apparently, `index.d.ts` on the latest alpha is effectively empty:
```
declare const _default;
export default _default;
```

**Comment by davidmurdoch** [comment]
Thanks for trying out the alpha. This is one of the known issues. Ganache bundles all dependencies (to minimize install time and reduce supply chain attacks), and bundling dependency types is not a completely solved problem yet. I'm hoping recent releases of https://github.com/microsoft/rushstack/tree/master/apps/api-extractor will solve enough of the problem now. We tried it, as well as libraries that are starting to solve the problem back in June and there were too many manual changes required.

**Comment by ukstv** [comment]
Good to know it's a known issue. Looking forward to having a type declaration in a GA release.

**Comment by ukstv** [comment]
BTW, @davidmurdoch I have an unrelated request/question. You guys merged 1559 support, but have not released a new alpha. This 1559 support is pretty huge thing, so IMO is worth a release albeit under alpha tag. How do you decide when to release something?

**Comment by davidmurdoch** [comment]
@ukstv 1559 support was released in alpha.1 on September 21st. Here are the release notes https://github.com/trufflesuite/ganache/releases#user-content-v7.0.0-alpha.1-highlights

**Comment by davidmurdoch** [comment]
@ukstv Since you didn't know we had released it, i'm sure others have missed this information as well. We probably need to expand our messaging about releases. Where did you check to see if there was a ganache release for 1559/London support? I'll try to ensure we have broader release exposure in the future.

**Comment by ukstv** [comment]
@davidmurdoch Maybe I do not understand what part of 1559 support landed in alpha.1.

alpha.1 was released 21 days ago, while https://github.com/trufflesuite/ganache/pull/1307 has been merged 13 days ago.

Current alpha.1 responds with a block that misses baseFee.

**Comment by davidmurdoch** [comment]
Ah, I see what you mean. Support for Type-2 (EIP-1559) transactions was released in alpha.1; there were some bugs in its implementation that will be fixed by #1307.
