### ISSUE TITLE
London support on npm

### ISSUE THREAD

**Issue by danhper** [ConsenSys-archive/ganache#1417]
Hi there :wave: 
I saw that London support has recently be pushed to the develop branch.
Is there any plan on having a release on npm soon?
Thanks!

**Comment by davidmurdoch** [comment]
You can try it now by installing ganache@alpha. Run:

```
npm uninstall ganache-cli --global
```

then

```
npm install ganache@alpha --global
```

Check the release notes here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1

**Comment by danhper** [comment]
Awesome, thanks!
