### ISSUE TITLE
ganache become super slow after thousands of transactions

### ISSUE THREAD

**Issue by gnomesaregreat** [ConsenSys-archive/ganache#1423]
I need to check my smart contract on millions of transactions,(1 by 1)
the problem is after around 10k transactions it takes more than 1 hour for a single transaction

that my command
>ganache-cli -d --db c:/chain/ -i 8888 --accounts 20  -e 100000 -l 22626085

**Comment by davidmurdoch** [comment]
@gnomesaregreat can you try the latest alpha version to see if it fixes it for you? The list of breaking changes and installation instructions are here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1

You may need to enable the --chain.legacyInstamine flag.

**Comment by gnomesaregreat** [comment]
> @gnomesaregreat can you try the latest alpha version to see if it fixes it for you? The list of breaking changes and installation instructions are here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1
> 
> You may need to enable the --chain.legacyInstamine flag.

Hi so now the mnemonic don't work but it did 40k transactions already and running fast  thanks(:

**Comment by davidmurdoch** [comment]
Hm, what is the full command (with the actual `mnemonic` redacted, if you need to) you are running that causes the mnemonic to not be applied?

**Comment by fainashalts** [comment]
Hi @gnomesaregreat just wanted to check in on this -- have you been able to get the mnemonic working? If so can you share what was going wrong? Thanks so much!

**Comment by gnomesaregreat** [comment]
i just remove them and didn't check them again,  
there are a few more commands that didn't work for me but it was a long time ago so I don't remember what. 
one thing that does happen a lot that if I send big transactions the rpc will get a lot of disconnect

**Comment by its-everdred** [comment]
Closing this for issue maintenance. If you try again and it doesn't work, please open a new issue and we'll be happy to help!
