### ISSUE TITLE
Forking on ganache programatically causes all requests to stall

### ISSUE THREAD

**Issue by moda20** [ConsenSys-archive/ganache#1458]
I am trying to create a forked new provider for web3 via the programmatic way of running ganache. but i encountered an issue where all my calls hang forever and never finish. here is how i am doing it:

```
const options = {
            fork:`${SOURCE_CHAIN_RPC_ENDPOINT@11997000`
        };
        const provider = ganache.provider(options);
        let x = new web3(provider, null, { transactionConfirmationBlocks: 1 });
        x.eth.getAccounts().then(console.log)
```

the getAccounts promise doesn't resolve ever, and all other calls have the same issue. is this a bug and if so, is there a workaround ?

**Comment by tuleyko** [comment]
+1, have the same bug

**Comment by davidmurdoch** [comment]
@moda20 and @tuleyko Can you try the ganache v7 alpha release and let me know if it fixes the issue for you? https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1

**Comment by moda20** [comment]
@davidmurdoch i tried the alpha when trying to debug this error, and it didn't solve my issue. But my issue was related to the forked provider as it wasn't an archive node, and the blockNumber I am using is more than 64 blocks in the past. so @tuleyko, maybe check your provider and see if it s an archive node or not.

**Comment by davidmurdoch** [comment]
@moda20 Did ganache v7 alpha at least error on start up instead of hang?

**Comment by moda20** [comment]
@davidmurdoch no I am pretty sure it did hang, but I don't remember if it printed an error message or not.

**Comment by fainashalts** [comment]
@tuleyko were you able to reproduce this bug using ganache 7? @moda20 can you give us some more reproduction steps if this is still a problem in ganache 7? We have been unable to reproduce.

**Comment by tuleyko** [comment]
Hey guys, I've tried to upgrade to alpha v7 but no success. There was a different error than initial. I had no time to wait and I redesigned my app not to use ganache at all

**Comment by kevinbluer** [comment]
Hey @tuleyko, thanks for the heads up. We'll go ahead and close for issue maintenance, although feel free to provide reproductions steps and we can re-open.
