### ISSUE TITLE
Add `eth_feeHistory` RPC endpoint

### ISSUE THREAD

**Issue by leroldary** [ConsenSys-archive/ganache#1470]
The `eth_feeHistory` API was  introduced in the [JSON-RPC](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) spec as a counterpart to EIP-1559. The API exposes information that is useful for setting parameters (`maxPriorityFeePerGas`, `maxFeePerGas`) for the new transaction fee mechanism.

**Comment by seaona** [comment]
+1! It would be very helpful to have support for `eth_feeHistory` in ganache

**Comment by davidmurdoch** [comment]
@seaona Would you like to add it?

**Comment by seaona** [comment]
@davidmurdoch sure! I'll try my best 😊

**Comment by drortirosh** [comment]
It is very problematic that ganache is partial eip-1559 `eth_feeHistory` is a required part of it.

**Comment by MicaiahReid** [comment]
@seaona any updates on a PR for this? No worries if you haven't been (or won't be) able to, just checking in.
