### ISSUE TITLE
Unexpected behaviour with StaticCall [eth_call]

### ISSUE THREAD

**Issue by wei3erHase** [ConsenSys-archive/ganache#1478]
StaticCall does not atomizes the transaction state changes when calling with `eth_call`. State variable that should be changed inside the transaction do not change when interacting with more than 1 contract.

Contract example: https://goerli.etherscan.io/address/0x26e4977a70d0E4262d1D731b7446B8527EB4E253#code

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.4 <0.9.0;

interface ICaller {
  function caller() external returns (address _caller);
}

interface IReturner {
  function returner() external returns (address _caller);
}

contract Returner is IReturner{
  function returner() external override returns (address _caller) {
    return ICaller(msg.sender).caller();
  }
}

contract TestState is ICaller{
  address public override caller;
  address public returner;

  constructor(address _returner) {
    returner = _returner;
  }

  modifier setsCaller() {
    caller = msg.sender;
    _;
    caller = address(0);
  }

  function viewState() external payable setsCaller() returns (bool) {
    require(IReturner(returner).returner() == msg.sender, 'REVERTS');
    return true;
  }

}
```

When calling `viewState` in TestState Contract, `caller` should be set to `msg.sender`, returner should call TestState and ask for `caller` and `viewState` is checking that Returner answer is in fact `msg.sender`.

The `viewState` function works if called from Etherscan (or Hardhat), it does not work when using Ganache's CallStatic (`eth_call`).

**Comment by davidmurdoch** [comment]
Which version of ganache are you using?

**Comment by wei3erHase** [comment]
```
    "ganache": "6.4.5",
    "ganache-core": "2.13.2",
```

**Comment by davidmurdoch** [comment]
Can you try installing `ganache@7.0.0-alpha.1` and using that? You'll need to uninstall `ganache-core` and change the import from `require("ganache-core")` to `require("ganache")` (or ` import "ganache-core"` to ` import "ganache"`). Let me know if you have questions about updating.

**Comment by wei3erHase** [comment]
that made the job! 🎉 

{\\__/}
( • . •)
/ > `<3`
