### ISSUE TITLE
Unexpected console.logs in production

### ISSUE THREAD

**Issue by wei3erHase** [ConsenSys-archive/ganache#1495]
`version v7.0.0-alpha.1` spawns `eth_call` and `eth_chainId` on each fork request

**Comment by davidmurdoch** [comment]
Hey, thanks for trying the alpha! Can you explain the issue a bit more?

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance.  Feel free to explain further though and we can perhaps reopen this.  Thanks!
