### ISSUE TITLE
eth_call should return JSON-RPC error on revert

### ISSUE THREAD

**Issue by domob1812** [ConsenSys-archive/ganache#1496]
When `eth_call` causes a transaction revert, the JSON-RPC method should return an error rather than a result that just contains the revert data.  Currently (using Ganache from git) `eth_call` returns data like this for a call that reverts:

    0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000008408c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000324552433732313a207472616e7366657220746f206e6f6e20455243373231526563656976657220696d706c656d656e746572000000000000000000000000000000000000000000000000000000000000000000000000000000000000

This seems to be basically the same issue that Geth had (and resolved) in https://github.com/ethereum/go-ethereum/issues/19027.

**Comment by davidmurdoch** [comment]
If you use ganache@7.0.0-alpha.1 I believe you can enable behavior by setting the `--chain.vmErrorsOnRPCResponse` flag on start up.

```
$ npm uninstall ganache-cli -g
$ npm install ganache@7.0.0-alpha.1 -g
$ ganache --chain.vmErrorsOnRPCResponse
```

Can you try that and let me know if it returns what you'd expect?

Perhaps we should make this the default mode for `eth_call`. /cc @MicaiahReid

**Comment by domob1812** [comment]
Thanks @davidmurdoch for pointing me to that flag - it indeed does what I need, so for me the issue is resolved.

But I can definitely say that from the point of view of a developer using Ganache's JSON-RPC interface, I certainly expected `eth_call` to throw in case of a revert, so it might make sense to turn that on by default.  (But of course just having the flag is good enough in practice.)

**Comment by davidmurdoch** [comment]
Yes, I think we agree that we should return the error by default. We likely copied our implementation of `eth_call` from geth before they changed and and we should follow suit to make it the default (and only!) behavior.
