### ISSUE TITLE
Close fork when process exits

### ISSUE THREAD

**Issue by 0xGorilla** [ConsenSys-archive/ganache#1530]
When calling `process.exit()` in order to close the current process, the forks still run on the background.

Is there any way you could subscribe to the exiting of the process from inside Ganache and self-close the forks?

**Comment by davidmurdoch** [comment]
This sounds like a bug to me! Are you able to provide a simple reproduction?

**Comment by davidmurdoch** [comment]
I'm unable to reproduce with this script:

```javascript
const ganache = require("ganache");
const provider = ganache.provider({
  fork: FORK_URL
});

(async function () {
  const balance = await provider.request({
    method: "eth_getBalance",
    params: [ "0xbcc817f057950b0df41206c5d7125e6225cae18e" ]
  });
  console.log(balance);
  process.exit();
})();
```

**Comment by 0xGorilla** [comment]
You are right, after lots of testing in a separate environment I did notice that this is working perfectly. Sorry for that!

**Comment by davidmurdoch** [comment]
No apology necessary! Thanks for all the feedback!
