### ISSUE TITLE
Incompatible `Provider` typings with `ethersjs`?

### ISSUE THREAD

**Issue by ndzik** [ConsenSys-archive/ganache#1534]
I was working on creating a minimal example for another issue. When I pulled up the README to start a new project I adapted the following code from the [docs](https://www.npmjs.com/package/ganache-core), which btw differ from what is seen in the README in this repository?):

```ts
const ganache = require("ganache-core");
const provider = new ethers.providers.Web3Provider(ganache.provider());
```

Of course I installed `ganache-core` with `yarn add -D ganache-core`. Since I was creating a minimal example either way you can check out the following [commit](https://github.com/ndzik/funwithganache/commit/583274fb5be0c5fc2dc0a075b3f7c9ab5a42073a).

Maybe I am just misunderstanding something so thanks in advance for the help.

**Comment by davidmurdoch** [comment]
Can you try with `ganache@alpha` (`yarn add -D ganache@alpha`) (also uninstall ganache-core and change the require/import to "ganache") and let me know if the included types work better for you?

**Comment by ndzik** [comment]
Glorious thanks! This solves it. Should the README be changed to incorporate such information or was I just blind and did not follow the steps correctly? :sweat_smile:

**Comment by davidmurdoch** [comment]
Our repos are just in a confusing state right now. `ganache-core` is the core of `ganache-cli`, which has moved to the [ganache-cli-archive](https://github.com/trufflesuite/ganache-cli-archive) repo. The readme of the `ganache` repo, which ganache-core redirects to, has a notice at the top directing users to the ganache-cli-archive repo.
