### ISSUE TITLE
Disabling logging on 7.0.0-alpha.1

### ISSUE THREAD

**Issue by rainwater11** [ConsenSys-archive/ganache#1581]
I am seeing several of these being logged to the console and would like to turn them off if possible:
eth_blockNumber
eth_chainId

How can I do this?

**Comment by davidmurdoch** [comment]
Looks like the `--quiet` flag has a bug. Thanks for reporting!

**Comment by rainwater11** [comment]
> Looks like the `--quiet` flag has a bug. Thanks for reporting!

Not a problem! Is there any way I can temporarily fix this?

**Comment by davidmurdoch** [comment]
On unix you can redirect all output to nothing: `ganache > /dev/null`. On Windows you may be able to use `ganache >NUL` (I haven't tried it myself).

**Comment by rainwater11** [comment]
> On unix you can redirect all output to nothing: `ganache > /dev/null`. On Windows you may be able to use `ganache >NUL` (I haven't tried it myself).

Ok but I am using Ganache programmatically and not launching from the command line.

**Comment by davidmurdoch** [comment]
Oh. You can pass your own logger to ganache:

```javascript
ganache.provider({ 
  logging: {
    logger: {
      log: () => {} // don't do anything
    }
  }
});
```

**Comment by rainwater11** [comment]
> Oh. You can pass your own logger to ganache:
> 
> ```js
> ganache.provider({ 
>   logging: {
>     logger: {
>       log: () => {} // don't do anything
>     }
>   }
> });
> ```

Hey that works!  Thank you!
