### ISSUE TITLE
Dockerfile not building for 7.0.0 beta as no script "clean" 

### ISSUE THREAD

**Issue by NikZak** [ConsenSys-archive/ganache#1629]
When I try to build the dockerfile here ``https://github.com/trufflesuite/ganache/tree/develop/src/packages/ganache``
*Dockerfile below*
```
# use full node to install dependencies
FROM node:14.17.4@sha256:cd98882c1093f758d09cf6821dc8f96b241073b38e8ed294ca1f9e484743858f AS builder

WORKDIR /app

COPY . .

# clean and install dependencies
RUN npm run clean
```

I get an error 
```
npm ERR! Missing script: "clean"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```
Indeed ``https://github.com/trufflesuite/ganache/blob/develop/src/packages/ganache/package.json`` does not have "clean" script. Available scripts are 
```
  "scripts": {
    "build": "npm run tsc && npx shx rm -rf ./dist && webpack",
    "tsc": "ttsc --build",
    "test": "nyc npm run mocha",
    "mocha": "cross-env TS_NODE_COMPILER=ttypescript TS_NODE_FILES=true mocha --exit --check-leaks --throw-deprecation --trace-warnings --require ts-node/register 'tests/**/*.test.ts'",
    "start": "cross-env TS_NODE_COMPILER=ttypescript node --require ts-node/register --inspect src/cli.ts"
  }
```

**Comment by davidmurdoch** [comment]
You have to build it from the root of the project:

```
docker build -t your-tag-here -f ./src/packages/ganache/Dockerfile .
```

You can also install it from docker hub: https://hub.docker.com/r/trufflesuite/ganache

**Comment by NikZak** [comment]
Thank you so much for pointing to the hub with latest releases and thanks for keeping it up to date! (Compilation on my Apple m1 still fails and I think this is memory related problem)
I was using this hub before https://hub.docker.com/r/trufflesuite/ganache-cli/tags because it is the one that is first found by google search but looks like it is not the active branch
Maybe you could insert the link to readme?

**Comment by davidmurdoch** [comment]
Good call. I've made an issue to do that here : https://github.com/trufflesuite/ganache/issues/1668

I don't have an M1 mac to test with myself. If you do figure out whats wrong with our dockerfile build on M1 please do let us know. Our build process does take a lot of memory right now, so that very well could be the constraint.
