### ISSUE TITLE
Support `eth_maxPriorityFeePerGas`

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1632]

**Comment by MatthiasLohr** [comment]
Any (rough) ETA how long it will take to make this available in beta Docker image?

**Comment by gnidan** [comment]
Soon!™†*

* your mileage may vary
† terms and conditions may apply

---

just kidding, we're working on it!

**Comment by MatthiasLohr** [comment]
That was fast! Thanks!

Any idea when the fix will be available in the Docker image on DockerHub? That would be awesome to have it there.
