### ISSUE TITLE
v7.0.0-beta.0 signing issue: Invalid signature v value

### ISSUE THREAD

**Issue by dhorkin** [ConsenSys-archive/ganache#1638]
I'm having trouble calling a smart contract method with v7.0.0-beta.0.

The same code executed against ganache-cli v6.12.2 works fine.

web3 code in question:
```
  const signedTx = await eth.accounts.signTransaction(
    transactionObject,
    ADMIN_ETH_KEY_1,
  );
  const txReceipt = await eth.sendSignedTransaction(signedTx.rawTransaction);
```

When this is run with ganache v7 beta, I get this: `Error: Returned error: Invalid signature v value`

It looks like the v value is 0x2d45 on ganache v6.12.2, but 0x2d46 on v7.0.0-beta-0.

Edit: `v7.0.0-alpha.2` has the same issue

Possibly related to https://github.com/trufflesuite/ganache/issues/972

**Comment by davidmurdoch** [comment]
Hm, interesting. I'll look into this today. Thanks for trying the beta and reporting on this issue!

**Comment by davidmurdoch** [comment]
Does your `transactionObject` contain a `chainId` property set to the _`chainId`_ of your ganache instance (the default is `1337`)?

If the `chainId` property is omitted from the `transactionObject` `web3` will [incorrectly use the `net_version` RPC call](https://web3js.readthedocs.io/en/v1.5.2/web3-eth-accounts.html#id4) instead of `eth_chainId` RPC call to get the `chainId` to sign the transaction with.

In ganache v6 we always allowed transactions to be signed with the `chainId`, the `networkId`, or `1` due to an accidental legacy bug turned feature. In v7 we have fixed the bug, which might break tests and libraries that relied on it. This ~breaking change~ bug fix was only briefly mentioned in the v7 alpha.0 [release notes](https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.0#user-content-v7.0.0-alpha.0-technically-bug-fixes-but-these-might-break-your-tests) ("chainId option defaults to 1337 everywhere"); we'll be sure to bring more attention to the matter in any future release notes.

Regarless of my hunch above, I've escalated both of these issues to Priority 1 as we may still have a bug here, or we may just need to improve our error message to make the issue more clear.

**Comment by davidmurdoch** [comment]
Note: I've started some testing and found that while web3's latest documentation (labeled v1.5.2) does state that it uses `net_version` it actually  uses `eth_chainId`(tested with web3@latest v1.6.1).

**Comment by davidmurdoch** [comment]
I can reproduce this issue if I set the `chainId` value in the `transactionObject` to `5777`, which is not the correct value for the `chainId` (it should be the result of calling `eth_chainId`).

Can you let me know if this is what is happening so I can either close this issue or continue investigating further?

**Comment by dhorkin** [comment]
It looks like we're setting `chainId` to the network ID. If I change that to the network ID, the signing issue goes away, but then we get `Error: Returned error: transaction underpriced` no matter what we put for gasPrice. I'm guessing Ganache v7 may have a bug with legacy transactions.

This code works on Rinkeby.

**Comment by davidmurdoch** [comment]
The `transaction underpriced` error should mean that you have sent a transaction with a nonce that matches that of a transaction already in the transaction pool, but whose `gasPrice` isn't high enough to actually replace the older transaction (it needs to be 10% greater, IIRC).

Are you trying to send a replacement transaction? (this wasn't supported at all with Ganache v6)

**Comment by dhorkin** [comment]
No, we're not trying to send a replacement transaction. I've tried absurd gasPrices and they still don't work.

Here's a slightly more complete picture of the web3 code:

```
  const tx_builder = contractInstance.methods.myFunctionName(
    userAddress,
    amount,
  );
  const encoded_tx = tx_builder.encodeABI();

  const transactionObject = {
    gasPrice: 50000000000,
    gasLimit: 3000000,
    chainId: CHAIN_ID, // this used to be NETWORK_ID, but that doesn't work with v7 ganache
    data: encoded_tx,
    to: contractInstance.options.address,
    from: ADMIN_ETH_ADDRESS_1,
  };

  const signedTx = await eth.accounts.signTransaction(
    transactionObject,
    ADMIN_ETH_KEY_1,
  );
  const txReceipt = await eth.sendSignedTransaction(signedTx.rawTransaction);
```

I've tried the following in **web3j (java)** and get the same error despite not explicitly setting any gas price:
`contract.myFunctionName(address, amount).send();`

**Comment by dhorkin** [comment]
I'm also getting a `transaction underpriced` error from metamask after trying to speed up or cancel a pending transaction (different contract call). The initial transaction in metamask has been sitting for 20 minutes without being mined, with no other traffic on ganache. With v6, this took far less than 1 minute in similar conditions.

Here's the parameters I'm passing to ganache: `--chain.chainId=1337 --chain.networkId=1337 --wallet.deterministic --database.dbPath=/ganache/db --wallet.totalAccounts=3 --wallet.defaultBalance=1000000000 --miner.blockTime=15`

**Comment by davidmurdoch** [comment]
It sounds like you've somehow skipped a nonce, which puts the transaction in the transaction pool until a transaction with the skipped nonce is sent. We'll need to figure out how a transaction with a nonce higher than intended got sent to ganache. Are you able to provide any additional information or a reproduction?

note: while investigating this we did find that our code to detect a replacement transaction is off by 1 wei (we use a `>` instead of `>=` check when comparing the transactions' gas prices). This will be fixed in a future release.

**Comment by dhorkin** [comment]
> It sounds like you've somehow skipped a nonce

I don't think this is what is happening. For one, v6 should have had the same behavior then.

In any case, we changed the code as follows and the problem went away. I'm pretty sure at this point that ganache v7 has a bug in how it handles legacy transactions:

Old version:
```
  const transactionObject = {    
    gasPrice: 50000000000,
    gasLimit: 3000000,
    chainId: CHAIN_ID,
    data: encoded_tx,
    to: contractInstance.options.address,
    from: ADMIN_ETH_ADDRESS_1,
  };
```
New version:
```
  const transactionObject = {
    gas: 3000000,
    chainId: CHAIN_ID,
    data: encoded_tx,
    to: contractInstance.options.address,
    from: ADMIN_ETH_ADDRESS_1,
  };
```

**Comment by davidmurdoch** [comment]
> v6 should have had the same behavior then.

Hmmm, `v6` does not support skipping nonces at all; the transaction doesn't get a chance to enter the pool.

Anyway, I'm not sure why sending a type 2 transaction (by removing `gasPrice`) affects things; I will need more reproduction steps to figure out what's going on here.


The following works for me with ganache@beta, so I wonder what else is going on with your tests and contracts that make it break.

```
const Web3 = require("web3");
const web3 = new Web3("http://localhost:8545");
(async () => {
  const signed = await web3.eth.accounts.signTransaction(
    {
      from: "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1",
      to: "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1",
      chainId: 1337,
      gasPrice: 50000000000,
      gasLimit: 3000000
    },
    "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
  );
  console.log(signed);
  const receipt = await web3.eth.sendSignedTransaction(signed.rawTransaction);
  console.log(receipt);
})();
```

I noticed you are using the `database.dbPath` option, so ganache picks up from where it left off. If you are hardcoding any nonces in your test code that could cause the issue we are seeing (though again, I don't know why that would be different from a type 2 transaction).

**Comment by dhorkin** [comment]
I'm happy to try and give more reproduction steps, but I don't know what you're looking for at this point - I gave a complete code sample with the exception of the contract code.

I'm running the `trufflesuite/ganache:v7.0.0-beta.0` docker image, if that helps.

No hardcoded nonces. The nonces are being figured out by web3, rather than being done manually.

I do appreciate you being very responsive on this, btw.

**Comment by davidmurdoch** [comment]
I'll take another shot at tracking it down in the morning with a fresh mind.

And thank you for being so responsive as well!

**Comment by davidmurdoch** [comment]
I've been unable to reproduce.

I have a reproduction script below. You will need to install `web3@1.6.1` and `solc@0.8.10` before running it.

Can you try this and let me know if it works for you? If it does work, can you see anything different with this code compared to yours that may affect the outcome?

 The ganache command (`dbPath` differs from yours to make it easier to run):
 
`ganache --chain.chainId=1337 --chain.networkId=1337 --wallet.deterministic --database.dbPath=./ganache-db --wallet.totalAccounts=3 --wallet.defaultBalance=1000000000 --miner.blockTime=15`

```javascript
const solc = require("solc");
const Web3 = require("web3");
const web3 = new Web3("http://localhost:8545");
(async () => {
  const compilation = JSON.parse(
    solc.compile(
      JSON.stringify({
        language: "Solidity",
        sources: {
          Test: {
            content: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.10;

contract Test {
  uint256 public value;

  function setValue(uint256 val) public {
    value = val;
  }
}`
          }
        },
        settings: {
          outputSelection: {
            "*": {
              "*": ["*"]
            }
          }
        }
      })
    )
  );

  const account = {
    address: "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1",
    key: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
  };

  const { contractAddress } = await web3.eth.sendTransaction({
    from: account.address,
    data: `0x${compilation.contracts.Test.Test.evm.bytecode.object}`,
    gasLimit: 12000000
  });
  console.log("contractAddress", contractAddress);

  const signed = await web3.eth.accounts.signTransaction(
    {
      to: contractAddress,
      data: `0x${
        compilation.contracts.Test.Test.evm.methodIdentifiers[
          "setValue(uint256)"
        ]
      }${"0".repeat(64)}`,
      chainId: 1337,
      gasPrice: 50000000000,
      gasLimit: 3000000
    },
    account.key
  );
  const receipt = await web3.eth.sendSignedTransaction(signed.rawTransaction);
  console.log("worked?", receipt.status === true);
})();
```

**Comment by MicaiahReid** [comment]
@FFdhorkin Have you been able to run @davidmurdoch's reproduction script above? We still haven't been able to reproduce this issue and we'd love to get this fixed while we're still in beta. Thanks again for all of the time you've taken in reporting/following up with us!

**Comment by dhorkin** [comment]
Code won't run.

`TypeError: soljson.cwrap is not a function` coming from `node_modules/solc/wrapper.js:13`

**Comment by davidmurdoch** [comment]
Can you make sure you have the latest version of solc, web3, and ganache installed and try again? What version of node are you using?

**Comment by davidmurdoch** [comment]
Closing for issue maintenance. If this is still an issue please comment below and we'll reopen it!
