### ISSUE TITLE
Ganache-cli command not found

### ISSUE THREAD

**Issue by JMiddey** [ConsenSys-archive/ganache#1771]
Hi I have been trying to get ganache-cli working for ages now but no luck, I have tried npm install g- ganache-cli aswell as trying to install it via yarn, both say that I have it installed but yet dont allow me to use the command to run it!

**Comment by davidmurdoch** [comment]
have you tried `npm install -g ganache-cli`? If so, can you paste the entire sequence of commands and their output here?

**Comment by JMiddey** [comment]
> have you tried `npm install -g ganache-cli`? If so, can you paste the entire sequence of commands and their output here?

joe@Joes-MacBook-Pro ~ % npm install -g ganache-cli

changed 6 packages, and audited 102 packages in 5s

2 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (7 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

this is what comes up, previously it has said that there is already this file already exists but now just shows this.

Edit:
then when I try this
joe@Joes-MacBook-Pro ~ % ganache-cli
zsh: command not found: ganache-cli
this comes up

**Comment by davidmurdoch** [comment]
did you previously run `npm install -g ganache@beta` (or @alpha)?

**Comment by JMiddey** [comment]
all I ran was npm install -g ganache-cli

**Comment by davidmurdoch** [comment]
Do you remember ever running `sudo npm install -g ...` (or otherwise running `npm install` as the super user)?

**Comment by JMiddey** [comment]
that might have been one of the things I tried, although im not sure!

**Comment by davidmurdoch** [comment]
The reason I ask is because `sudo npm install ...` will change the permissions of the npm folder and can cause problems.

It sounds like your npm and or node installation is broken. Can you try uninstalling node (and npm), and then install https://github.com/nvm-sh/nvm to manage your node versions?

**Comment by JMiddey** [comment]
I am trying to uninstall node and npm, although npm doesn't seem to be uninstalling and I dont have a node.js application downloaded. Also, from your link, is it just running this line of code?
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

**Comment by JMiddey** [comment]
I have tried to uninstall and reinstall everything, although there are ganache versions that I cannot uninstall for some reason, they are -

and now when I run ganache-cli I get this message:
joe@Joes-MacBook-Pro web3_py_siimple_storage % npm ls
joe@ /Users/joe
├── g@2.0.1
├── ganache-cli@6.5.0 invalid: "^6.12.2" from the root project
└── ganache@7.0.0-alpha.2

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:527949)
    at b.set (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:528548)
    at Function.b.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:530917)
    at Function.i.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:526525)
    at new S (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:206543)
    at new p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:195647)
    at new l (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:13485)
    at Object.create (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:94:92509)
    at Object.server (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:38637)
    at Object.<anonymous> (/Users/joe/.config/yarn/global/node_modules/ganache-cli/cli.js:106:22)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by davidmurdoch** [comment]
run `npm uninstall g -g && npm uninstall ganache -g && npm uninstall ganache-cli -g` then try `npm install ganache-cli -g` again.

**Comment by JMiddey** [comment]
joe@Joes-MacBook-Pro web3_py_siimple_storage % npm uninstall g -g && npm uninstall ganache -g && npm uninstall ganache-cli -g

up to date, audited 1 package in 91ms

found 0 vulnerabilities

up to date, audited 1 package in 88ms

found 0 vulnerabilities

up to date, audited 1 package in 90ms

found 0 vulnerabilities
joe@Joes-MacBook-Pro web3_py_siimple_storage % npm install ganache-cli -g                                                    

added 1 package, and audited 102 packages in 3s

2 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (7 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
joe@Joes-MacBook-Pro web3_py_siimple_storage % ganache-cli                                                                   
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:527949)
    at b.set (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:528548)
    at Function.b.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:530917)
    at Function.i.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:526525)
    at new S (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:206543)
    at new p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:195647)
    at new l (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:13485)
    at Object.create (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:94:92509)
    at Object.server (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:38637)
    at Object.<anonymous> (/Users/joe/.config/yarn/global/node_modules/ganache-cli/cli.js:106:22)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

this is what happens when I do that

**Comment by JMiddey** [comment]
So I have managed to uninstall what i think is everything and reinstall it, however I am still/having permission errors, any way to change it so that I have permission?

**Comment by JMiddey** [comment]
from what I can tell the issue is to do with ganache(correct me if i'm wrong) as here in all of my npm packages they are all green with "extraneous" as opposed to ganache:
joe@Joes-MacBook-Pro web3_py_simple_storage % npm ls
joe@ /Users/joe
├── @types/bn.js@4.11.6 extraneous
├── @types/node@16.11.6 extraneous
├── @types/pbkdf2@3.1.0 extraneous
├── @types/secp256k1@4.0.3 extraneous
├── ansi-regex@4.1.0 extraneous
├── ansi-styles@3.2.1 extraneous
├── base-x@3.0.9 extraneous
├── blakejs@1.1.1 extraneous
├── browserify-aes@1.2.0 extraneous
├── bs58@4.0.1 extraneous
├── bs58check@2.1.2 extraneous
├── buffer-from@1.1.2 extraneous
├── buffer-xor@1.0.3 extraneous
├── camelcase@5.3.1 extraneous
├── cipher-base@1.0.4 extraneous
├── cliui@5.0.0 extraneous
├── color-convert@1.9.3 extraneous
├── color-name@1.1.3 extraneous
├── create-hash@1.2.0 extraneous
├── create-hmac@1.1.7 extraneous
├── cross-spawn@6.0.5 extraneous
├── decamelize@1.2.0 extraneous
├── emoji-regex@7.0.3 extraneous
├── end-of-stream@1.4.4 extraneous
├── ethereum-cryptography@0.1.3 extraneous
├── ethereumjs-util@6.2.1 extraneous
├── ethjs-util@0.1.6 extraneous
├── evp_bytestokey@1.0.3 extraneous
├── execa@1.0.0 extraneous
├── find-up@3.0.0 extraneous
├── g@2.0.1
├── ganache-cli@6.12.2
├── ganache@7.0.0-alpha.2
├── get-caller-file@2.0.5 extraneous
├── get-stream@4.1.0 extraneous
├── hash-base@3.1.0 extraneous
├── invert-kv@2.0.0 extraneous
├── is-fullwidth-code-point@2.0.0 extraneous
├── is-hex-prefixed@1.0.0 extraneous
├── is-stream@1.1.0 extraneous
├── isexe@2.0.0 extraneous
├── lcid@2.0.0 extraneous
├── locate-path@3.0.0 extraneous
├── map-age-cleaner@0.1.3 extraneous
├── md5.js@1.3.5 extraneous
├── mem@4.3.0 extraneous
├── mimic-fn@2.1.0 extraneous
├── nice-try@1.0.5 extraneous
├── npm-run-path@2.0.2 extraneous
├── once@1.4.0 extraneous
├── os-locale@3.1.0 extraneous
├── p-defer@1.0.0 extraneous
├── p-finally@1.0.0 extraneous
├── p-is-promise@2.1.0 extraneous
├── p-limit@2.3.0 extraneous
├── p-locate@3.0.0 extraneous
├── p-try@2.2.0 extraneous
├── path-exists@3.0.0 extraneous
├── path-key@2.0.1 extraneous
├── pbkdf2@3.1.2 extraneous
├── pump@3.0.0 extraneous
├── randombytes@2.1.0 extraneous
├── readable-stream@3.6.0 extraneous
├── require-directory@2.1.1 extraneous
├── require-main-filename@2.0.0 extraneous
├── ripemd160@2.0.2 extraneous
├── rlp@2.2.7 extraneous
├── safe-buffer@5.2.1 extraneous
├── scrypt-js@3.0.1 extraneous
├── semver@5.7.1 extraneous
├── set-blocking@2.0.0 extraneous
├── setimmediate@1.0.5 extraneous
├── sha.js@2.4.11 extraneous
├── shebang-command@1.2.0 extraneous
├── shebang-regex@1.0.0 extraneous
├── signal-exit@3.0.6 extraneous
├── source-map-support@0.5.12 extraneous
├── source-map@0.6.1 extraneous
├── string_decoder@1.3.0 extraneous
├── string-width@3.1.0 extraneous
├── strip-ansi@5.2.0 extraneous
├── strip-eof@1.0.0 extraneous
├── strip-hex-prefix@1.0.0 extraneous
├── util-deprecate@1.0.2 extraneous
├── which-module@2.0.0 extraneous
├── which@1.3.1 extraneous
├── wrap-ansi@5.1.0 extraneous
├── wrappy@1.0.2 extraneous
├── y18n@4.0.3 extraneous
├── yargs-parser@13.1.2 extraneous
└── yargs@13.2.4 extraneous

**Comment by davidmurdoch** [comment]
Can you navigate to `/Users/joe/.config/yarn/global/node_modules/` and delete ganache and ganache-cli from there then try again?

**Comment by JMiddey** [comment]
There isnt a .config/yarn path on my laptop, instead they are all in /Users/joe/node_modules (apart from yarn which is in /joe/bin), there was one cli.js file in one of the folders in the yard path which I have now deleted and then reinstalled using both npm and yarn, the following error comes up:

joe@Joes-MacBook-Pro web3_py_simple_storage % npm install -g ganache-cli

added 1 package, and audited 102 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (7 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
joe@Joes-MacBook-Pro web3_py_simple_storage % ganache-cli
zsh: command not found: ganache-cli
joe@Joes-MacBook-Pro web3_py_simple_storage % npm ls
joe@ /Users/joe
├── @trufflesuite/bigint-buffer@1.1.9 extraneous
├── @types/bn.js@4.11.6 extraneous
├── @types/node@16.11.6 extraneous
├── @types/pbkdf2@3.1.0 extraneous
├── @types/secp256k1@4.0.3 extraneous
├── abstract-leveldown@6.2.3 extraneous
├── ansi-regex@4.1.0 extraneous
├── ansi-styles@3.2.1 extraneous
├── base-x@3.0.9 extraneous
├── base64-js@1.5.1 extraneous
├── blakejs@1.1.1 extraneous
├── bn.js@4.12.0 extraneous
├── brorand@1.1.0 extraneous
├── browserify-aes@1.2.0 extraneous
├── bs58@4.0.1 extraneous
├── bs58check@2.1.2 extraneous
├── buffer-from@1.1.2 extraneous
├── buffer-xor@1.0.3 extraneous
├── buffer@5.7.1 extraneous
├── bufferutil@4.0.3 extraneous
├── camelcase@5.3.1 extraneous
├── cipher-base@1.0.4 extraneous
├── cliui@5.0.0 extraneous
├── color-convert@1.9.3 extraneous
├── color-name@1.1.3 extraneous
├── create-hash@1.2.0 extraneous
├── create-hmac@1.1.7 extraneous
├── cross-spawn@6.0.5 extraneous
├── decamelize@1.2.0 extraneous
├── elliptic@6.5.4 extraneous
├── emoji-regex@7.0.3 extraneous
├── end-of-stream@1.4.4 extraneous
├── ethereum-cryptography@0.1.3 extraneous
├── ethereumjs-util@6.2.1 extraneous
├── ethjs-util@0.1.6 extraneous
├── evp_bytestokey@1.0.3 extraneous
├── execa@1.0.0 extraneous
├── find-up@3.0.0 extraneous
├── UNMET DEPENDENCY g@^2.0.1
├── UNMET DEPENDENCY ganache-cli@^6.12.2
├── UNMET DEPENDENCY ganache@^7.0.0-alpha.2
├── get-caller-file@2.0.5 extraneous
├── get-stream@4.1.0 extraneous
├── hash-base@3.1.0 extraneous
├── hash.js@1.1.7 extraneous
├── hmac-drbg@1.0.1 extraneous
├── ieee754@1.2.1 extraneous
├── immediate@3.3.0 extraneous
├── inherits@2.0.4 extraneous
├── invert-kv@2.0.0 extraneous
├── is-fullwidth-code-point@2.0.0 extraneous
├── is-hex-prefixed@1.0.0 extraneous
├── is-stream@1.1.0 extraneous
├── isexe@2.0.0 extraneous
├── keccak@3.0.1 extraneous
├── lcid@2.0.0 extraneous
├── level-concat-iterator@2.0.1 extraneous
├── level-supports@1.0.1 extraneous
├── leveldown@5.6.0 extraneous
├── locate-path@3.0.0 extraneous
├── map-age-cleaner@0.1.3 extraneous
├── md5.js@1.3.5 extraneous
├── mem@4.3.0 extraneous
├── mimic-fn@2.1.0 extraneous
├── minimalistic-assert@1.0.1 extraneous
├── minimalistic-crypto-utils@1.0.1 extraneous
├── napi-macros@2.0.0 extraneous
├── nice-try@1.0.5 extraneous
├── node-addon-api@2.0.2 extraneous
├── node-gyp-build@4.2.3 extraneous
├── npm-run-path@2.0.2 extraneous
├── once@1.4.0 extraneous
├── os-locale@3.1.0 extraneous
├── p-defer@1.0.0 extraneous
├── p-finally@1.0.0 extraneous
├── p-is-promise@2.1.0 extraneous
├── p-limit@2.3.0 extraneous
├── p-locate@3.0.0 extraneous
├── p-try@2.2.0 extraneous
├── path-exists@3.0.0 extraneous
├── path-key@2.0.1 extraneous
├── pbkdf2@3.1.2 extraneous
├── pump@3.0.0 extraneous
├── randombytes@2.1.0 extraneous
├── readable-stream@3.6.0 extraneous
├── require-directory@2.1.1 extraneous
├── require-main-filename@2.0.0 extraneous
├── ripemd160@2.0.2 extraneous
├── rlp@2.2.7 extraneous
├── safe-buffer@5.2.1 extraneous
├── scrypt-js@3.0.1 extraneous
├── secp256k1@4.0.2 extraneous
├── semver@5.7.1 extraneous
├── set-blocking@2.0.0 extraneous
├── setimmediate@1.0.5 extraneous
├── sha.js@2.4.11 extraneous
├── shebang-command@1.2.0 extraneous
├── shebang-regex@1.0.0 extraneous
├── signal-exit@3.0.6 extraneous
├── source-map-support@0.5.12 extraneous
├── source-map@0.6.1 extraneous
├── string_decoder@1.3.0 extraneous
├── string-width@3.1.0 extraneous
├── strip-ansi@5.2.0 extraneous
├── strip-eof@1.0.0 extraneous
├── strip-hex-prefix@1.0.0 extraneous
├── utf-8-validate@5.0.4 extraneous
├── util-deprecate@1.0.2 extraneous
├── which-module@2.0.0 extraneous
├── which@1.3.1 extraneous
├── wrap-ansi@5.1.0 extraneous
├── wrappy@1.0.2 extraneous
├── xtend@4.0.2 extraneous
├── y18n@4.0.3 extraneous
├── yargs-parser@13.1.2 extraneous
└── yargs@13.2.4 extraneous

npm ERR! code ELSPROBLEMS
npm ERR! extraneous: @trufflesuite/bigint-buffer@1.1.9 /Users/joe/node_modules/@trufflesuite/bigint-buffer
npm ERR! extraneous: @types/bn.js@4.11.6 /Users/joe/node_modules/@types/bn.js
npm ERR! extraneous: @types/node@16.11.6 /Users/joe/node_modules/@types/node
npm ERR! extraneous: @types/pbkdf2@3.1.0 /Users/joe/node_modules/@types/pbkdf2
npm ERR! extraneous: @types/secp256k1@4.0.3 /Users/joe/node_modules/@types/secp256k1
npm ERR! extraneous: abstract-leveldown@6.2.3 /Users/joe/node_modules/abstract-leveldown
npm ERR! extraneous: ansi-regex@4.1.0 /Users/joe/node_modules/ansi-regex
npm ERR! extraneous: ansi-styles@3.2.1 /Users/joe/node_modules/ansi-styles
npm ERR! extraneous: base-x@3.0.9 /Users/joe/node_modules/base-x
npm ERR! extraneous: base64-js@1.5.1 /Users/joe/node_modules/base64-js
npm ERR! extraneous: blakejs@1.1.1 /Users/joe/node_modules/blakejs
npm ERR! extraneous: bn.js@4.12.0 /Users/joe/node_modules/bn.js
npm ERR! extraneous: brorand@1.1.0 /Users/joe/node_modules/brorand
npm ERR! extraneous: browserify-aes@1.2.0 /Users/joe/node_modules/browserify-aes
npm ERR! extraneous: bs58@4.0.1 /Users/joe/node_modules/bs58
npm ERR! extraneous: bs58check@2.1.2 /Users/joe/node_modules/bs58check
npm ERR! extraneous: buffer-from@1.1.2 /Users/joe/node_modules/buffer-from
npm ERR! extraneous: buffer-xor@1.0.3 /Users/joe/node_modules/buffer-xor
npm ERR! extraneous: buffer@5.7.1 /Users/joe/node_modules/buffer
npm ERR! extraneous: bufferutil@4.0.3 /Users/joe/node_modules/bufferutil
npm ERR! extraneous: camelcase@5.3.1 /Users/joe/node_modules/camelcase
npm ERR! extraneous: cipher-base@1.0.4 /Users/joe/node_modules/cipher-base
npm ERR! extraneous: cliui@5.0.0 /Users/joe/node_modules/cliui
npm ERR! extraneous: color-convert@1.9.3 /Users/joe/node_modules/color-convert
npm ERR! extraneous: color-name@1.1.3 /Users/joe/node_modules/color-name
npm ERR! extraneous: create-hash@1.2.0 /Users/joe/node_modules/create-hash
npm ERR! extraneous: create-hmac@1.1.7 /Users/joe/node_modules/create-hmac
npm ERR! extraneous: cross-spawn@6.0.5 /Users/joe/node_modules/cross-spawn
npm ERR! extraneous: decamelize@1.2.0 /Users/joe/node_modules/decamelize
npm ERR! extraneous: elliptic@6.5.4 /Users/joe/node_modules/elliptic
npm ERR! extraneous: emoji-regex@7.0.3 /Users/joe/node_modules/emoji-regex
npm ERR! extraneous: end-of-stream@1.4.4 /Users/joe/node_modules/end-of-stream
npm ERR! extraneous: ethereum-cryptography@0.1.3 /Users/joe/node_modules/ethereum-cryptography
npm ERR! extraneous: ethereumjs-util@6.2.1 /Users/joe/node_modules/ethereumjs-util
npm ERR! extraneous: ethjs-util@0.1.6 /Users/joe/node_modules/ethjs-util
npm ERR! extraneous: evp_bytestokey@1.0.3 /Users/joe/node_modules/evp_bytestokey
npm ERR! extraneous: execa@1.0.0 /Users/joe/node_modules/execa
npm ERR! extraneous: find-up@3.0.0 /Users/joe/node_modules/find-up
npm ERR! missing: g@^2.0.1, required by joe@
npm ERR! missing: ganache-cli@^6.12.2, required by joe@
npm ERR! missing: ganache@^7.0.0-alpha.2, required by joe@
npm ERR! extraneous: get-caller-file@2.0.5 /Users/joe/node_modules/get-caller-file
npm ERR! extraneous: get-stream@4.1.0 /Users/joe/node_modules/get-stream
npm ERR! extraneous: hash-base@3.1.0 /Users/joe/node_modules/hash-base
npm ERR! extraneous: hash.js@1.1.7 /Users/joe/node_modules/hash.js
npm ERR! extraneous: hmac-drbg@1.0.1 /Users/joe/node_modules/hmac-drbg
npm ERR! extraneous: ieee754@1.2.1 /Users/joe/node_modules/ieee754
npm ERR! extraneous: immediate@3.3.0 /Users/joe/node_modules/immediate
npm ERR! extraneous: inherits@2.0.4 /Users/joe/node_modules/inherits
npm ERR! extraneous: invert-kv@2.0.0 /Users/joe/node_modules/invert-kv
npm ERR! extraneous: is-fullwidth-code-point@2.0.0 /Users/joe/node_modules/is-fullwidth-code-point
npm ERR! extraneous: is-hex-prefixed@1.0.0 /Users/joe/node_modules/is-hex-prefixed
npm ERR! extraneous: is-stream@1.1.0 /Users/joe/node_modules/is-stream
npm ERR! extraneous: isexe@2.0.0 /Users/joe/node_modules/isexe
npm ERR! extraneous: keccak@3.0.1 /Users/joe/node_modules/keccak
npm ERR! extraneous: lcid@2.0.0 /Users/joe/node_modules/lcid
npm ERR! extraneous: level-concat-iterator@2.0.1 /Users/joe/node_modules/level-concat-iterator
npm ERR! extraneous: level-supports@1.0.1 /Users/joe/node_modules/level-supports
npm ERR! extraneous: leveldown@5.6.0 /Users/joe/node_modules/leveldown
npm ERR! extraneous: locate-path@3.0.0 /Users/joe/node_modules/locate-path
npm ERR! extraneous: map-age-cleaner@0.1.3 /Users/joe/node_modules/map-age-cleaner
npm ERR! extraneous: md5.js@1.3.5 /Users/joe/node_modules/md5.js
npm ERR! extraneous: mem@4.3.0 /Users/joe/node_modules/mem
npm ERR! extraneous: mimic-fn@2.1.0 /Users/joe/node_modules/mimic-fn
npm ERR! extraneous: minimalistic-assert@1.0.1 /Users/joe/node_modules/minimalistic-assert
npm ERR! extraneous: minimalistic-crypto-utils@1.0.1 /Users/joe/node_modules/minimalistic-crypto-utils
npm ERR! extraneous: napi-macros@2.0.0 /Users/joe/node_modules/napi-macros
npm ERR! extraneous: nice-try@1.0.5 /Users/joe/node_modules/nice-try
npm ERR! extraneous: node-addon-api@2.0.2 /Users/joe/node_modules/node-addon-api
npm ERR! extraneous: node-gyp-build@4.2.3 /Users/joe/node_modules/node-gyp-build
npm ERR! extraneous: npm-run-path@2.0.2 /Users/joe/node_modules/npm-run-path
npm ERR! extraneous: once@1.4.0 /Users/joe/node_modules/once
npm ERR! extraneous: os-locale@3.1.0 /Users/joe/node_modules/os-locale
npm ERR! extraneous: p-defer@1.0.0 /Users/joe/node_modules/p-defer
npm ERR! extraneous: p-finally@1.0.0 /Users/joe/node_modules/p-finally
npm ERR! extraneous: p-is-promise@2.1.0 /Users/joe/node_modules/p-is-promise
npm ERR! extraneous: p-limit@2.3.0 /Users/joe/node_modules/p-limit
npm ERR! extraneous: p-locate@3.0.0 /Users/joe/node_modules/p-locate
npm ERR! extraneous: p-try@2.2.0 /Users/joe/node_modules/p-try
npm ERR! extraneous: path-exists@3.0.0 /Users/joe/node_modules/path-exists
npm ERR! extraneous: path-key@2.0.1 /Users/joe/node_modules/path-key
npm ERR! extraneous: pbkdf2@3.1.2 /Users/joe/node_modules/pbkdf2
npm ERR! extraneous: pump@3.0.0 /Users/joe/node_modules/pump
npm ERR! extraneous: randombytes@2.1.0 /Users/joe/node_modules/randombytes
npm ERR! extraneous: readable-stream@3.6.0 /Users/joe/node_modules/readable-stream
npm ERR! extraneous: require-directory@2.1.1 /Users/joe/node_modules/require-directory
npm ERR! extraneous: require-main-filename@2.0.0 /Users/joe/node_modules/require-main-filename
npm ERR! extraneous: ripemd160@2.0.2 /Users/joe/node_modules/ripemd160
npm ERR! extraneous: rlp@2.2.7 /Users/joe/node_modules/rlp
npm ERR! extraneous: safe-buffer@5.2.1 /Users/joe/node_modules/safe-buffer
npm ERR! extraneous: scrypt-js@3.0.1 /Users/joe/node_modules/scrypt-js
npm ERR! extraneous: secp256k1@4.0.2 /Users/joe/node_modules/secp256k1
npm ERR! extraneous: semver@5.7.1 /Users/joe/node_modules/semver
npm ERR! extraneous: set-blocking@2.0.0 /Users/joe/node_modules/set-blocking
npm ERR! extraneous: setimmediate@1.0.5 /Users/joe/node_modules/setimmediate
npm ERR! extraneous: sha.js@2.4.11 /Users/joe/node_modules/sha.js
npm ERR! extraneous: shebang-command@1.2.0 /Users/joe/node_modules/shebang-command
npm ERR! extraneous: shebang-regex@1.0.0 /Users/joe/node_modules/shebang-regex
npm ERR! extraneous: signal-exit@3.0.6 /Users/joe/node_modules/signal-exit
npm ERR! extraneous: source-map-support@0.5.12 /Users/joe/node_modules/source-map-support
npm ERR! extraneous: source-map@0.6.1 /Users/joe/node_modules/source-map
npm ERR! extraneous: string_decoder@1.3.0 /Users/joe/node_modules/string_decoder
npm ERR! extraneous: string-width@3.1.0 /Users/joe/node_modules/string-width
npm ERR! extraneous: strip-ansi@5.2.0 /Users/joe/node_modules/strip-ansi
npm ERR! extraneous: strip-eof@1.0.0 /Users/joe/node_modules/strip-eof
npm ERR! extraneous: strip-hex-prefix@1.0.0 /Users/joe/node_modules/strip-hex-prefix
npm ERR! extraneous: utf-8-validate@5.0.4 /Users/joe/node_modules/utf-8-validate
npm ERR! extraneous: util-deprecate@1.0.2 /Users/joe/node_modules/util-deprecate
npm ERR! extraneous: which-module@2.0.0 /Users/joe/node_modules/which-module
npm ERR! extraneous: which@1.3.1 /Users/joe/node_modules/which
npm ERR! extraneous: wrap-ansi@5.1.0 /Users/joe/node_modules/wrap-ansi
npm ERR! extraneous: wrappy@1.0.2 /Users/joe/node_modules/wrappy
npm ERR! extraneous: xtend@4.0.2 /Users/joe/node_modules/xtend
npm ERR! extraneous: y18n@4.0.3 /Users/joe/node_modules/y18n
npm ERR! extraneous: yargs-parser@13.1.2 /Users/joe/node_modules/yargs-parser
npm ERR! extraneous: yargs@13.2.4 /Users/joe/node_modules/yargs

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joe/.npm/_logs/2021-12-08T11_33_09_186Z-debug.log

**Comment by JMiddey** [comment]
Ok so I have managed to play around with it a bit and now when I input ganache-cli I get this:
joe@Joes-MacBook-Pro web3_py_simple_storage % ganache-cli
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:527949)
    at b.set (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:528548)
    at Function.b.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:530917)
    at Function.i.fromMasterSeed (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:526525)
    at new S (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:206543)
    at new p (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:195647)
    at new l (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:13485)
    at Object.create (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:94:92509)
    at Object.server (/Users/joe/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:38637)
    at Object.<anonymous> (/Users/joe/.config/yarn/global/node_modules/ganache-cli/cli.js:106:22)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by davidmurdoch** [comment]
What version of ganache? And what version of node?

**Comment by JMiddey** [comment]
joe@Joes-MacBook-Pro web3_py_simple_storage % ganache-cli --version
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
joe@Joes-MacBook-Pro web3_py_simple_storage % node -v
v17.2.0

**Comment by davidmurdoch** [comment]
Use node 12 or 14 with the ganache-cli package. The `ganache` packed will work on node 17.

**Comment by JMiddey** [comment]
omg thank you so much, this worked! I appreciate the help a lot! this caused me a lot of frustration but finally I can carry on with my work!😂 thanks again you helped a lot!

**Comment by JMiddey** [comment]
I am now having an error with the solcx module not being found but im guessing thats for another thread😅

**Comment by davidmurdoch** [comment]
Ganache doesn't use a `solcx` module, as far as I'm aware. Do you mean `solcx`?

**Comment by JMiddey** [comment]
Yeah so the ganache module is working but now the file im trying to run requires solcx and even though when I hover over 'solcx' it says (module) solcx, when I run the file I get line 1, in <module>
Import solcx
InportError: No module named solcx
