### ISSUE TITLE
Runtime storage inconsistency if revert is involved

### ISSUE THREAD

**Issue by vasapower** [ConsenSys-archive/ganache#1835]
Hello all, I've encountered a really annoying storage problem __at runtime__ while using `ganache-core@2.13.2` [(this one)](https://www.npmjs.com/package/ganache-core).

Let's suppose to have these Contracts:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract SRC {
    DST public dst = new DST();

    event DSTVal(uint256 step, uint256 value);

    function execute(bool alsoRevert) external {
        emit DSTVal(0, dst.val());

        dst.inc();

        emit DSTVal(1, dst.val());

        if(alsoRevert) {
            address(dst).call(abi.encodeWithSelector(dst.doRevert.selector));
        }

        emit DSTVal(2, dst.val());
    }
}

contract DST {

    uint256 public val;

    function inc() external {
        val++;
    }

    function doRevert() external {
        revert('Ad hoc revert');
    }
}
```

I've tested and deployed them on Rinkeby:
[SRC](https://rinkeby.etherscan.io/address/0x9913b40194068a7a6930e04baee768774d62eaf2)
[DST](https://rinkeby.etherscan.io/address/0x34e37193c92a4e66369e0f5d4bfc1da35723fa70)

1) After creation, `dst.val()` is `0`, of course;
    
2) When `src.execute(false);` is called for the first time, the values of the 3 `DSTVal` events raised are:
```
    DSTVal(0, 0);
    DSTVal(1, 1);
    DSTVal(2, 1);
```
and, of course, the following `dst.val()` call will give back `1`;  [TXN](https://rinkeby.etherscan.io/tx/0x561c68ec1edeb597da9aa7da8dcd5851342dbfda7b998d6030570ff45bac8d1b#eventlog)
    
3) When `src.execute(true);` is called, a catched `revert` action occurs, and the values of the 3 `DSTVal` events raised are, of course:
```
    DSTVal(0, 1);
    DSTVal(1, 2);
    //correctly catched revert occurs
    DSTVal(2, 2);
```
again, of course, the following `dst.val()` call will correctly give back `2`;  [TXN](https://rinkeby.etherscan.io/tx/0xbbb64fa98e608860820f07247164a3460b4165b8fcb214282e8176c33fe59ab8#eventlog)

But on Ganache, if you replay the transaciton at point 3) (no matter if redeploying everything from scratch in a brand new network or by forking the Rinkeby network at block #`9823113`), the 3 `DSTVal` events raised are:
```
    DSTVal(0, 1);
    DSTVal(1, 2);
    //correctly catched revert occurs
    DSTVal(2, 1); //<--- DST storage state rolls back to the previous value
```

The problem still remains even if I replace the `call` with a `try/catch` statement or even with another scenario involving `staticcall`.

So it's like Ganache (or maybe the `ethereumjs-vm` implementation) catches the `revert` action properly, but reverts the storage state in any case.

The strangest thing is that, as I wrote in the title of this issue, __this is just a Runtime mistake__.

In fact, if you call the `dst.val()` method after this transaction, __it still gives you back the correct result, which is `2`__.

Although the example I made previously is for explanation purposes only,

I've encountered this problem in a more serious scenario:

```
erc20Token.transferFrom(msg.sender, address(this), value);//<-- grab some tokens from the sender

address(erc20Token).staticcall(abi.encodeWithSelector(erc20Token.potentialRevertCatchedCall.selector));//<- In my specific case, this call can revert in some circumstances, so I need to catch it

erc20Token.transfer(finalTokenDestination, value);//<-- in Ganache, if the previous call reverts, erc20Token state rolls back and this call reverts too throwing "insufficient balance" error, which cannot be possible because of the transferFrom statement at first line. It of course works correctly in non-Ganache environments (both mainnet and testnets).
```

After spending almost an entire day to find and understand the problem, I've successfully solved it just putting the `erc20Token.transfer(finalTokenDestination, value);` line __before__ the one that could revert. 

But there could be really a lot of scenarios where this action cannot be possible.

Have you already encountered a similar problem? Is there already a solution, in your opinion?

Thanks

**Comment by davidmurdoch** [comment]
Can you try with `ganache@7.0.0-beta.1` and let me know if it is still an issue? Release notes: https://github.com/trufflesuite/ganache/releases/tag/untagged-e163081359db6c575b3e

**Comment by vasapower** [comment]
> Can you try with `ganache@7.0.0-beta.1` and let me know if it is still an issue? Release notes: https://github.com/trufflesuite/ganache/releases/tag/untagged-e163081359db6c575b3e

I confirm you that the version `7.0.0-beta.1` __solves__ this problem.
![image](https://user-images.githubusercontent.com/5588727/146422487-7f6b3e45-f83b-4e21-b304-c3c93d229624.png)

**Comment by davidmurdoch** [comment]
Awesome to hear that! Thanks for giving the beta a try!
