### ISSUE TITLE
Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by aldwnesx** [ConsenSys-archive/ganache#1845]
I am trying to connect web3js in the javascript section of my html to my ganache-cli nodejs server

ganache deployment script:

```javascript
const ganache = require("ganache-cli");
const Web3 = require("web3");
const web3 = new Web3(ganache.provider());

const { interface, bytecode } = require("./compile");

const deploy = async () => {
  const accounts = await web3.eth.getAccounts();

  const result = await new web3.eth.Contract(JSON.parse(interface))
    .deploy({
      data: bytecode,
      arguments: ["test"],
    })
    .send({ from: accounts[0], gas: "1000000" });

  console.log(`Contract address: ${result.options.address}`);

};

var server = ganache.server();

server.listen(8545, function (err, blockchain) {
  console.log(server);
  console.log(" live at port 8545");
});

deploy();
```

test function calls script:

```javascript
testCall= async () => {
  var info = await new web3.eth.Contract(
    JSON.parse(interface),
    "0xa7f6564165e081116B3822016b522dFf96551F9E"
  );
    const message = await info.methods
    .GetInfo("test1")
    .call({ from: accounts[0] });

     console.log(message); };
```

I get the following error:

`(node:21204) UnhandledPromiseRejectionWarning: Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.`

The weird thing is, I can call function that sends data:

```javascript
 var test1 = await info.methods
      .SetInfo("test", "test", "test", "test", "", "", "")
     .send({
       from: accounts[0],
       gas: "1000000",
      });

     console.log(test1);
```

However whenever I try to call GetInfo() it never ever works. I have ensured the ABI and contract address is valid. It works for the SetInfo function, so I have no clue why it doesn't work on GetInfo.

```solidity
function GetInfo(string _DO) public view returns (string memory) {
        // return (AllInfo[_DO].status,AllInfo[_DO].time);
                return "hi";

    }   
```

**Comment by haltman-at** [comment]
It's hard to say what's going wrong here without more detailed reproduction steps.  Do you possibly have a reproduction example we could check out?  Thanks!

**Comment by haltman-at** [comment]
Closing this for issue maintenance.  Please let us know if there's still an issue here.
