### ISSUE TITLE
Add a way to create or modify arbitrary accounts and storage

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1889]
We can already create empty accounts, and set their nonce*, but we can't set their balance, code, or storage.

\* Related: https://github.com/trufflesuite/ganache/issues/1646

**Comment by rmeissner** [comment]
This issue seems to be a partial duplicate of https://github.com/trufflesuite/ganache/issues/649

**Comment by MicaiahReid** [comment]
Implemented by #2337.
