### ISSUE TITLE
blockchain.queueTransaction: getting revert reason

### ISSUE THREAD

**Issue by t-anyu** [ConsenSys-archive/ganache#1922]
Hey,

I'm very new to ganache and don't know all the reasonings, but I stumbled on

if (this.#instamine && this.#options.miner.legacyInstamine) { ... }

Since legacyInstamine will be deprecated, I wonder if this should be if (this.#instamine && this.#options.chain.vmErrorsOnRPCResponse) in the future? My motivation is that I'd like to get revert reason on eth_sendTransaction in instamine mode. Alternatively, are there other simple ways to get it? Except using CPU-intensive ganache:vm:step emitter?

Thanks

**Comment by davidmurdoch** [comment]
You can get the revert reason by replaying the transaction as an `eth_call`.

**Comment by cds-amal** [comment]
Closing for issue maintenance. Please let us know if you'd like to reopen.
