### ISSUE TITLE
Strange crash with RangeError: invalid string length

### ISSUE THREAD

**Issue by mesozoic-technology** [ConsenSys-archive/ganache#1968]
I'm using Ganache CLI v6.12.2 (ganache-core: 2.13.2)

Here's my brownie logs for this problem. Right at the top you see a transaction which reverts and that's exactly what I want. But after that, every time, ganache crashes. It takes a snapshot, gets a trace transaction, and increases the time? What's going on here? Is this my fault or ganache's?

```
  Transaction: 0xa9505e1bb7f5cebfd7b79628f41f3e5c4c41495e9e4fb5b7291bf5399231703d
  Gas usage: 420261
  Block Number: 29
  Block Time: Wed Oct 06 2021 07:33:43 GMT-0400 (Eastern Daylight Time)
  Runtime Error: revert
  Revert reason: OVLV1:!liquidatable

eth_getTransactionByHash
eth_getTransactionCount
eth_getTransactionReceipt
debug_traceTransaction
evm_snapshot
Saved snapshot #32
debug_traceTransaction
evm_increaseTime
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at /Users/realisation/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:94:96641
    at /Users/realisation/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:14963
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
````

**Comment by davidmurdoch** [comment]
This looks like it'd be Ganache's fault. This is probably occuring because debug_traceTransaction here results in a response greater than ~1GB. The debug_traceTransaction issue is fixed in Ganache v7 beta. Can you try it out and let me know if it fixes it for you? Release notes here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-beta.2

**Comment by mesozoic-technology** [comment]
Interesting, why would the trace transaction suddenly be so large? It would be good to know this because I did just make substantial changes to my code. If that limit is the only problem, maybe no big deal. But still, strange and worrying.

**Comment by mesozoic-technology** [comment]
Ok, I've installed this next version and I've begun to run my brownie test, but it is taking forever, slowly printing out a deluge of `eth_getTransactionByHash`. Below is an example. This was maybe ten minutes ago and it's still printing out `eth_getTransactionByHash`. This is the only part where it looks like the code associated with my tests was actually running. 


```
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
web3_clientVersion
web3_clientVersion
eth_getBlockByNumber
web3_clientVersion
eth_blockNumber
eth_blockNumber
web3_clientVersion
web3_clientVersion
web3_clientVersion
web3_clientVersion
eth_getBlockByNumber
evm_snapshot
Saved snapshot #3
eth_accounts
eth_blockNumber
web3_clientVersion
eth_blockNumber
evm_revert
Reverting to snapshot #3
eth_blockNumber
evm_snapshot
Saved snapshot #3
evm_increaseTime
eth_blockNumber
eth_blockNumber
eth_getBlockByNumber
eth_getTransactionCount
eth_gasPrice
eth_getBlockByNumber
eth_sendTransaction
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
eth_getTransactionByHash
```

**Comment by davidmurdoch** [comment]
Try enabling ganache's `legacyInstamine` mode: `ganache --miner.legacyInstamine`

**Comment by davidmurdoch** [comment]
> Interesting, why would the trace transaction suddenly be so large? It would be good to know this because I did just make substantial changes to my code. If that limit is the only problem, maybe no big deal. But still, strange and worrying.

I'm not sure what is causing it now, perhaps a very large loop?

**Comment by mesozoic-technology** [comment]
Yeah shouldn't be. I mainly put some storage variables onto a struct in a central place, accessing that and passing them to inherited contracts. Should be pretty similar from my current understanding.

**Comment by mesozoic-technology** [comment]
Now I get this: 

```
E       ValueError: VM Exception while processing transaction: Transaction's maxFeePerGas (0) is less than the block's baseFeePerGas (875000000) (vm hf=london -> block -> tx)
```

**Comment by davidmurdoch** [comment]
Under london hardfork rules transactions can no longer specify a gasPrice of `0` (which is used to compute `maxFeePerGas`). If you don't care about london's EIP-1159 for your tests (ignoring EIP-1559 changes) you can just start ganache with the `istanbul` hardfork instead of the default (`london):  `ganache --chain.hardfork istanbul`

**Comment by cds-amal** [comment]
Closing for issue maintenance. Please let us know if this is still an issue
