### ISSUE TITLE
Figure out how to handle instamine over HTTP

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#1996]
There is no way to subscribe to `newHeads` over HTTP connections, so it becomes impossible for the user to detect when a new block is created (when a transaction is mined) without polling -- which is slow.

One way to "fix" this is to always mine transactions sent over HTTP as if Ganache was in `legacyInstamine` mode (instead of just `instamine` mode).

**Comment by kevinbluer** [comment]
Closing because it's not a high priority and unclear if it's even a problem any more.
