### ISSUE TITLE
The command '/bin/sh -c npm run build' returned a non-zero code: 2

### ISSUE THREAD

**Issue by johnfelipe** [ConsenSys-archive/ganache#2032]
root@eh68221471013:~/ganache# docker build --tag trufflesuite/ganache --file ./src/packages/ganache/Dockerfile .
	Sending build context to Docker daemon  437.9MB
	Step 1/16 : FROM node:14.17.4@sha256:cd98882c1093f758d09cf6821dc8f96b241073b38e8ed294ca1f9e484743858f AS builder
	 ---> 7528ad312b56
	Step 2/16 : WORKDIR /app
	 ---> Using cache
	 ---> 8b1b651629fb
	Step 3/16 : COPY . .
	 ---> Using cache
	 ---> 5ed77e4d1cf4
	Step 4/16 : RUN npm run clean
	 ---> Using cache
	 ---> 5893b6bc8c75
	Step 5/16 : RUN npm ci --unsafe-perm
	 ---> Using cache
	 ---> 991d92c1a56a
	Step 6/16 : ARG INFURA_KEY
	 ---> Using cache
	 ---> 3fd247bccc7f
	Step 7/16 : RUN npm run build
	 ---> Running in 98df9e59f2aa

	> root@ build /app
	> npm run tsc && cross-env NODE_OPTIONS=--max_old_space_size=4096 lerna run build

	> root@ tsc /app
	> tsc --build src

	lerna notice cli v4.0.0
	lerna info versioning independent
	lerna info Executing command in 3 packages: "npm run build"
	lerna ERR! npm run build exited 2 in 'ganache'
	lerna ERR! npm run build stdout:

	> ganache@7.0.0-beta.2 build /app/src/packages/ganache
	> npm run tsc && npx shx rm -rf ./dist && webpack && npm run types

	> ganache@7.0.0-beta.2 tsc /app/src/packages/ganache
	> tsc --build

	lerna ERR! npm run build stderr:
	[webpack-cli] Failed to load '/app/src/packages/ganache/webpack.config.ts' config
	[webpack-cli] Error: The `INFURA_KEY` environment variable was not supplied at build time. To bypass this check set the environment variable `CREATE_BROKEN_BUILD` to `"I WILL NOT PUBLISH THIS"`.
		at Object.<anonymous> (/app/src/packages/ganache/webpack/webpack.common.config.ts:21:9)
		at Module._compile (internal/modules/cjs/loader.js:1072:14)
		at Module.m._compile (/app/src/packages/ganache/node_modules/ts-node/src/index.ts:1371:23)
		at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
		at Object.require.extensions.<computed> [as .ts] (/app/src/packages/ganache/node_modules/ts-node/src/index.ts:1374:12)
		at Module.load (internal/modules/cjs/loader.js:937:32)
		at Function.Module._load (internal/modules/cjs/loader.js:778:12)
		at Module.require (internal/modules/cjs/loader.js:961:19)
		at require (internal/modules/cjs/helpers.js:92:18)
		at Object.<anonymous> (/app/src/packages/ganache/webpack/webpack.browser.config.ts:1:1)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! ganache@7.0.0-beta.2 build: `npm run tsc && npx shx rm -rf ./dist && webpack && npm run types`
	npm ERR! Exit status 2
	npm ERR!
	npm ERR! Failed at the ganache@7.0.0-beta.2 build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2022-01-11T08_38_42_434Z-debug.log
	lerna ERR! npm run build exited 2 in 'ganache'
	lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 2
	npm ERR! root@ build: `npm run tsc && cross-env NODE_OPTIONS=--max_old_space_size=4096 lerna run build`
	npm ERR! Exit status 2
	npm ERR!
	npm ERR! Failed at the root@ build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2022-01-11T08_38_42_472Z-debug.log
	The command '/bin/sh -c npm run build' returned a non-zero code: 2

how solve this?

**Comment by davidmurdoch** [comment]
The `INFURA_KEY` environment variable was not supplied at build time. To bypass this check set the environment variable `CREATE_BROKEN_BUILD` to `"I WILL NOT PUBLISH THIS"`.

Sorry about this, we need to update the documentation here.

**Comment by johnfelipe** [comment]
can u explain better, that env is directly into command prompt or where?

**Comment by davidmurdoch** [comment]
`CREATE_BROKEN_BUILD="I WILL NOT PUBLISH THIS" docker build...`

This will create a build, but the zero-config forking feature won't work.

Is there as reason you are building your own docker image instead of using the published one on docker hub?

**Comment by johnfelipe** [comment]
I rerun work cli in Ubuntu but I want to have cheatsheet with docker
standalone
Can u update pls documentation .MD file
Tnks

**Comment by davidmurdoch** [comment]
I don't understand what you are trying to do here. But if you want to run your own docker build you must follow the instructions I sent above.

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. Please open another issue if this is still happening.
