### ISSUE TITLE
Punch Out list for v7 stable release

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#2053]
### Must do before release:

- [x] Review blog post
- [x] Review and schedule the announcement tweet (if someone uses a bit.ly link instead of trfl.io/g7 for this I'll die)
  - [x] this needs a cool image. /cc @CombsieZ 
- [x] ~~Update website banner~~ Merge [website banner PR](https://github.com/trufflesuite/trufflesuite.com/pull/1146)
- [x] Merge [Docs PR](https://github.com/trufflesuite/ganache/pull/1759)
- [x] Update automatic release script to work with `master`
- [x] Write release notes
  - don't forget: this should encourage devs to "Star" the GitHub repo
- [x] Write and publish a v6-v7 upgrade guide

## Immediately after release
 - [x] undeprecate ganache@latest on npm
 - [x] Publish new Truffle version with Ganache v7

## Immediately before blog post
- [x] Post release notes then update the trfl.io/g7 to point to the latest release notes

### Can be done soon after release:

- [x] Post in discord (https://discord.gg/vbx6jy6XC8) and in [gitter](https://gitter.im/ConsenSys/truffle)
   - this will be taken care of by @lsqproduction
- [x] Post in ConsenSys slack about release
- [x] Deprecate ganache-cli and ganache-core npm packages
- [x] Archive ganache-cli-archived github repo (update readme to point to new location first)
- [x] Develop and produce swag for those who contributed to Ganache v7 (pre `rc.0`) /cc @CombsieZ 
     - in progress

**Comment by ghost** [comment]
Hello! Here's what marketing is working on to support the release :)

- [x] Truffle Blog: Tutorial

- [x] Docs update
David confirmed that Ganache docs (overview and quickstart) will be updated by Wed 1/19.

- [ ] Product Demo Video
Kingsley to deliver draft by 1/18 for review

- [ ] Sponsorship Video on Eat The Blocks
To be delivered on Friday

- [ ] Infura Community Call guest spot
David to demo Ganache 7 on Jan. 25

- [x] Social media threads

- [x] Product Email Update for Truffle list
Trish to work with Sunny on distro

- [x] Product Email Update for Infura list

- [x] Product Email Update for Academy list

- [ ] Academy Training Content Update

- [ ] Community Content Update

- [x] Infura.io [Blogpost](https://blog.infura.io/fork-ethereum-replay-historical-transactions-with-ganache-7-archive-support/) on Ganache + Infura integration
