### ISSUE TITLE
Add option to set fork block's timestamp to the time the actual block was mined

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#2122]
See: https://github.com/mds1/convex-shutdown-simulation/issues/7

**Comment by MicaiahReid** [comment]
When forking, we currently set the "latest" block's timestamp to the user's current time. This can be a big gap from the previous "latest" block's (the fork block) timestamp. Add the option to auto-set that timestamp to the fork block's timestamp + 1.

**Comment by davidmurdoch** [comment]
fixed by #3131
