### ISSUE TITLE
Ganache's provider type is not compatible with Web3

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#2125]
it's a matter of
`(payload: JsonRpcRequest<...>, callback?: Callback | undefined)`
(the relevant part of the type on Ganache)
vs
`(payload: JsonRPCRequest, callback: Callback<JsonRPCResponse>)`

Full error:

```
    test/encoder.test.ts:76:50 - error TS2345: Argument of type 'EthereumProvider_2' is not assignable to parameter of type 'Provider'.
      Types of property 'send' are incompatible.
        Type '{ <Method extends never>(method: Method, params?: NoUnknownArray<Parameters<Overloads<EthereumApi[Method]>>> | undefined): cleanAndMergePromiseGenerics<...>; <Method extends never>(payload: JsonRpcRequest<...>, callback?: Callback | undefined): undefined; <Method extends never>(payloads: JsonRpcRequest<...>[], callb...' is not assignable to type '(payload: JsonRPCRequest, callback: Callback<JsonRPCResponse>) => any'.
          Types of parameters 'params' and 'callback' are incompatible.
            Type 'Callback<JsonRPCResponse>' is not assignable to type 'undefined'.
            ```

**Comment by MicaiahReid** [comment]
Blocked until this web3 PR is merged. https://github.com/ChainSafe/web3.js/pull/4743

**Comment by koraykoska** [comment]
@MicaiahReid As it is merged already, is there any update?

**Comment by davidmurdoch** [comment]
@koraykoska You can try the new web3 release candidate that contains their fix now: https://github.com/ChainSafe/web3.js/releases/tag/v1.7.2-rc.0

**Comment by koraykoska** [comment]
@davidmurdoch I am not using web3.js. It's a dependency of ganache and I only use ganache with ethers.

**Comment by davidmurdoch** [comment]
Web3 is most certainly not a dependency of Ganache. 😁

Are you suggesting ethers doesn't like the Ganache provider type?

**Comment by koraykoska** [comment]
Yes, so at least Typescript can’t compile properly.

**Comment by davidmurdoch** [comment]
What is the error?

**Comment by koraykoska** [comment]
Pretty much what is described here:
https://githubhot.com/repo/trufflesuite/ganache-core/issues/2134

I get exactly the same errors and the last working version is 7.0.0-beta.1

**Comment by davidmurdoch** [comment]
Does adding `"skipLibCheck": true` temporarily fix it for you?

**Comment by MicaiahReid** [comment]
I've confirmed that types from Ganache v7.0.2 and above are compatible with web3 v1.7.3.
