### ISSUE TITLE
Shutting down the Ganache Server v7.0.0

### ISSUE THREAD

**Issue by PeterYinusa** [ConsenSys-archive/ganache#2185]
Platform: macOS Big Sur 11.6
Ganache Version: v7.0.0
Node: v14.17.0 
npm: v6.14.13

Description:

Server does not shut down with `Ctrl` + `C`

Steps to reproduce:

1. Run a test build of [MetaMask](https://github.com/MetaMask/metamask-extension#building-locally) by running `yarn build:test`
2. In a separate terminal start Ganache by running `ganache`
3. Press `Ctrl` + `C` to shutdown the server

Expected result:
Ganache Server is shut down

Actual result:
Ganache Server continues running after receiving the shutdown signal

Notes:
[Video attachment](https://drive.google.com/file/d/1uHM4SR7pvEF0xnKFLCe1GCJTlhWboGpW/view?usp=sharing)

Tested the following versions in the screen capture above.

Ganache CLI v6.12.2 (ganache-core: 2.13.2)

- Server shuts down immediately 

ganache v7.0.0 (@ganache/cli: 0.1.1, @ganache/core: 0.1.1)

- Server continues running

**Comment by haltman-at** [comment]
Wondering: Is the issue that it *doesn't* shut down, or that it takes a while to do so?  I'd noticed the latter problem, but somehow didn't think to file an issue about it.

**Comment by davidmurdoch** [comment]
Related: https://github.com/uNetworking/uWebSockets.js/issues/663#issuecomment-1026283415

**Comment by davidmurdoch** [comment]
@haltman-at It's actually both.

If a client sends a request with a `Connection: Keep Alive` header, and the client:

1) keeps the connection alive for n seconds and
2) always uses the connection _before_ n seconds have elapsed (like polling for the block number every 20 seconds)

then the socket connection will never been closed by the client.

When MetaMask is open it checks both of those boxes and will keep us from shutting down.

Ganache doesn't currently force close long-lived keep alive HTTP sessions when the server is closed, so the Node process remains active until the socket closes on it's own... which sometimes never occurs.

We're working on fixing this from a couple of different angles and will update this issue as we do.

**Comment by jeffsmale90** [comment]
@davidmurdoch I looked into various approaches to responding to this, and pushed an interim change to https://github.com/trufflesuite/ganache/commit/54b38e023edf039860b6edfbb55f0017e47b5f43

Once close() is called, all subsequent responses will have `end(body, closeConnection: true)` called. This will require a change to the .js fallback in uws-js-unofficial to support the `closeConnection` parameter https://github.com/trufflesuite/uws-js-unofficial/blob/786f94341a22e40e5afeff47b818066b9222ca86/src/fallback/http-response.ts#L110. It's obviously not ideal, but I cannot see a way to directly close the underlying connection outside of the context of a request/response from the client.

As mentioned in https://github.com/uNetworking/uWebSockets.js/issues/663#issuecomment-1026352121 worst case is probably 10s.

I wanted to get your feedback on the approach before I pursue this further.
