### ISSUE TITLE
Architecture not supported

### ISSUE THREAD

**Issue by canoqb10** [ConsenSys-archive/ganache#2256]
I am trying install ganache by npm cli and it throws the next error

I am on Mac OSX 10.156.7 Catalina
Macbook Pro 12-inch Mid 2012
with nvm and node v14..16.1
and npm v8.3.0

however I can install ganache ui with out troubles.

code 1
npm ERR! path /Users/albertocano/.nvm/versions/node/v12.18.0/lib/node_modules/ganache/node_modules/leveldown
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@14.16.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/albertocano/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/albertocano/.nvm/versions/node/v12.18.0/lib/node_modules/ganache/node_modules/leveldown/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/albertocano/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/albertocano/Library/Caches/node-gyp/14.16.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/albertocano/Library/Caches/node-gyp/14.16.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/albertocano/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/albertocano/Library/Caches/node-gyp/14.16.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/albertocano/.nvm/versions/node/v12.18.0/lib/node_modules/ganache/node_modules/leveldown',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../deps/leveldb/leveldb-1.20/db/builder.cc:5:
npm ERR! In file included from ../deps/leveldb/leveldb-1.20/db/builder.h:8:
npm ERR! In file included from ../deps/leveldb/leveldb-1.20/include/leveldb/status.h:16:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:504:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
npm ERR! In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:61:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:32:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
npm ERR! #error Unsupported architecture

**Comment by davidmurdoch** [comment]
You state node 14 but your error is using node 12. Though it should work on both. Additionally, node 14 comes with npm v6, so it looks like you may have manually downgraded to npm v8. And while it possible and unfortunately common to install npm v8 on old node versions, v8 can be very buggy.

Can you try installing npm 6 (npm install npm@6 -g) and trying again? If that doesn't work, can you clarify your system stats and what command you are running to do the install?

**Comment by khelil** [comment]
Having exactly the same error, had to downgrade npm to make it work.
Here some tests:
❌ node v14.18.1 (npm v8.5.1)
❌ node v10.15.3 (npm v7.5.4)
✅ node v11.1.0 (npm v6.5.0)

**Comment by davidmurdoch** [comment]
This may be fixed by #3208 in the next release

**Comment by tenthirtyone** [comment]
@canoqb10 @khelil Any luck with the latest ganache after the update that included https://github.com/trufflesuite/ganache/pull/3208

**Comment by MicaiahReid** [comment]
Closing because this seems to be fixed!
