### ISSUE TITLE
Building project with tsc fails due to error in Ganache typings

### ISSUE THREAD

**Issue by rmeissner** [ConsenSys-archive/ganache#2300]
I try to build a library that depends on Ganache v7. When I run `tsc` I get a bunch of errors for the typings generation.

Node version: 16.9.1 (tried also with 12)
Ganache version: 7.0.2

Compiler output:
```sh
yarn run v1.22.17
$ rimraf dist && tsc
node_modules/ganache/dist/ganache.d.ts:2162:8 - error TS1005: ',' expected.

2162 removed: Buffer,
            ~

node_modules/ganache/dist/ganache.d.ts:2163:17 - error TS1005: ',' expected.

2163 transactionIndex: Buffer,
                     ~

node_modules/ganache/dist/ganache.d.ts:2164:16 - error TS1005: ',' expected.

2164 transactionHash: Buffer,

[...]

node_modules/ganache/dist/ganache.d.ts:12178:28 - error TS1005: ',' expected.

12178 declare type TxType = [type: Buffer];
                                 ~

node_modules/ganache/dist/ganache.d.ts:12180:25 - error TS1110: Type expected.

12180 declare type TxType_2 = `0x${HexChar}` | `0x${HexPair}`;
                              ~~~~~


Found 81 errors.

``` 

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": false,
    "esModuleInterop": true
  },
  "exclude": [
    "node_modules",
    "**/*.test.ts",
    "examples"
  ]
}
```

Not sure if related to the known issues regarding typings.

**Comment by davidmurdoch** [comment]
I'm working on [this issue](https://github.com/trufflesuite/ganache/issues/2134)  now. You can work around this for now by enabling skipLibCheck in your ts config. https://www.typescriptlang.org/tsconfig/skipLibCheck.html

**Comment by davidmurdoch** [comment]
This might just be a problem with typescript versions. Are you on an old version?

**Comment by rmeissner** [comment]
Yes it was actually an old typescript version (3.8.3 compared to 4.5.4). Thanks for the quick help ... is there a way to make `yarn` warn me about this?

**Comment by davidmurdoch** [comment]
I don't think there is a way to specify TS version ranges, unfortunately. (let me know if you find out!)

**Comment by rmeissner** [comment]
I only found https://github.com/microsoft/TypeScript/pull/26568 on SO. You basically would set the default types to one that throws an error and overwrite for a specific version the type definition to the correct one. Seems a little hacky :grimacing: 

Edit: Docs for `typesVersion`: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
