### ISSUE TITLE
may i ask you new package repo

### ISSUE THREAD

**Issue by gintering1000** [ConsenSys-archive/ganache#2346]
id like to install ganache-cli for terminal by homebrew without npm install.

for example : brew install ganache-cli
( it doesn't mean "cask" )

may i ask you new feature?

**Comment by davidmurdoch** [comment]
No, we don't support brew. If we did, we would have to install npm and node in order to get ganache to work.

**Comment by gintering1000** [comment]
ok i will ask this to downstream. : (
