### ISSUE TITLE
Notifications not supported: code 32004

### ISSUE THREAD

**Issue by fabianorodrigo** [ConsenSys-archive/ganache#2350]
Guys,

I was running this dapp perfectly using the Brave browser and Metamask plugin until the beginning of this week. Then, suddenly, it starts to behavior not as expected. Probably there was some automatic Brave update that I didn't noticed. So I disabled the Metamask plugin in order to make use of the Brave's native wallet and it got worst, I received the following error:

```
{
    "code": -32004,
    "message": "notifications not supported",
    "stack": "Error: notifications not supported\n    at Connector.<anonymous> (/home/fabianorodrigo/.nvm/versions/node/v16.14.0/lib/node_modules/ganache/dist/node/1.js:2:51891)\n    at Connector.handle (/home/fabianorodrigo/.nvm/versions/node/v16.14.0/lib/node_modules/ganache/dist/node/1.js:2:52493)\n    at /home/fabianorodrigo/.nvm/versions/node/v16.14.0/lib/node_modules/ganache/dist/node/1.js:2:207049"
}
```
What caught my attention and is the reason I'm opening this issue is the path in the message that points to my Ganache installation. Is this expected? Is the Brave wallet making use of some protocol not supported by Ganache?

PS: Running the same dapp on Firefox and Metamask plugin works perfectly.

Thank you very much for any clarification.

Best regards,

**Comment by davidmurdoch** [comment]
Does the Brave wallet URL start with `http` or `ws`?

**Comment by davidmurdoch** [comment]
Ah, I bet Brave Wallet forwards requests like `eth_subscribe` to the connected network (like Ganache) directly, but Brave Wallet _itself_ isn't connected to the `localhost` over WebSockets. The "notifications" error message happens when a client attempts to subscribe via eth_subscribe, but over HTTP instead of WebSockets, which just isn't possible.

**Comment by eggplantzzz** [comment]
Closing for issue maintenance, thanks!
