### ISSUE TITLE
Ganache binding to all network interfaces even with `-h localhost`

### ISSUE THREAD

**Issue by robsmith11** [ConsenSys-archive/ganache#2358]
When I run
```ganache --fork -n -h localhost```
I see the following with `lsof`:
```node    488738 root   20u  IPv6 28301584      0t0  TCP *:8545 (LISTEN)```
Because I'm running it on a popular cloud VM without a firewall, I also get a flood of people trying to steal the forked ETH.

**Comment by davidmurdoch** [comment]
Confirmed this a bug and I've found the issue. We'll get a fix out for this next week!
