### ISSUE TITLE
About transaction execution performances

### ISSUE THREAD

**Issue by emeraldbrown** [ConsenSys-archive/ganache#2392]
In Ganache v7.0.2, is `eth_sendTransaction` faster and "lighter" than `eth_sendRawTransaction`? Or the transaction speed depends on its own "weight" (in terms of operations/gas use)?

Sometimes both calls hang for a very long time.

Also, I've experimented speed differences between `provider` and `server` mode.

Is that possible?

Thanks

**Comment by davidmurdoch** [comment]
can you provide a reproduction?

**Comment by emeraldbrown** [comment]
Unfortunately it is an extreme randomic behavior to be reproduced. All that I can say is that the slowness in transaction submit (`eth_sendTransaction`/`eth_sendRawTransaction`) is frequent in `server` mode, even with just one client connected.

**Comment by davidmurdoch** [comment]
Might you be sending transactions with the nonce set too high?

**Comment by eggplantzzz** [comment]
Closing for issue maintenance.
