### ISSUE TITLE
`ganache --miner.defaultTransactionGasLimit estimate` fails with Error `Cannot convert estimate to a BigInt`

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#2398]
`defaultTransactionGasLimit` cli coercion function needs to take the string `"estimate"` into account when attempting to parse the raw option value.

**Comment by MicaiahReid** [comment]
@davidmurdoch, just to confirm, is this a typo on the title? `ganache --miner.blockGasLimit` should not accept `"estimate"` as an input value. Like your issue description says, we care about `--miner.defaultTransactionGasLimit`, right?

**Comment by davidmurdoch** [comment]
Sounds like a typo. Maybe everything works fine?

**Comment by MicaiahReid** [comment]
Nope, `ganache --miner.defaultTransactionGasLimit estimate` fails with the error specified above. (so does `ganache --miner.blockGasLimit estimate`, but I don't think we want that one to work)
