### ISSUE TITLE
Is there a sample for an array type startup option?

### ISSUE THREAD

**Issue by 3rdstage** [ConsenSys-archive/ganache#2429]
A few startup options including `--wallet.accounts` and `--wallet.unlockedAccount` are "array" type.  But array format - comma separated, space separated, enclosing bracket needed or ... - for startup option is not clear.

If I would like to unlock preceding 5 accounts, which one is correct ?

```
--wallet.totalAccounts 10 --wallet.unlockedAccount 0 1 2 3 4
--wallet.totalAccounts 10 --wallet.unlockedAccount 0, 1, 2, 3, 4
--wallet.totalAccounts 10 --wallet.unlockedAccount [0, 1, 2, 3, 4]
--wallet.totalAccounts 10 --wallet.unlockedAccount "0 1  2 3 4"
```

**Comment by davidmurdoch** [comment]
Use `--wallet.unlockedAccounts 0 --wallet.unlockedAccounts 1 --wallet.unlockedAccounts 2`

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance, thanks!
