### ISSUE TITLE
Unable to Install ganache-cli using yarn!

### ISSUE THREAD

**Issue by cyai** [ConsenSys-archive/ganache#2440]
I tried to install ganache-cli using the command `yarn global add ganache-cli` but was unable to do so!!!

SOLVED: Try installing ganache-cli using node.js itself by command `npm install -g ganache-cli`

**Comment by dongmingh** [comment]
Hi @cyai, ganache-cli (v6) is no longer supported.  Please install ganache (v7),
`npm uninstall ganache-cli && npm install -g ganache` instead.
Thanks!
