### ISSUE TITLE
Instantly mined transactions

### ISSUE THREAD

**Issue by bgokcol** [ConsenSys-archive/ganache#2481]
Hi. I'm using **sendTransaction** with Web3. I need instantly mined transactions but even if I use blockTime = 0 it takes 2 seconds. Is there any way to mine transactions instantly (or less than 1 second)?

**Comment by davidmurdoch** [comment]
They are mined instantly. It sounds like Web3 is polling for blocks.

What version of Ganache are you using and what are you start up parameters for it?

**Comment by bgokcol** [comment]
Hi @davidmurdoch, first of all thank you for the reply. I also think so, it's probably a problem because of Web3. I tried to set pollinginterval to 1 but not worked.

**Versions:**
+-- ganache@7.0.2
+-- web3@3.0.0-rc.5

**My startup options:**
```js
const options = {
    fork: {
        url: 'https://bsc-dataseed.binance.org'
    },
    miner: {
        blockTime: 0
    }
}

const provider = ganache.provider(options);

const gWeb3 = new Web3(provider, null, {
    transactionConfirmationBlocks: 1,
    pollingInterval: 1,
    transactionPollingInterval: 1,
    transactionReceiptPollingInterval: 1,
});
```

My Code:
```js
await gWeb3.addAccount(data.from, '');
await gWeb3.eth.personal.unlockAccount(data.from, '');
let t = (+new Date());
await gWeb3.eth.sendTransaction({
from: data.from,
to: data.to,
value: data.value,
data: data.input
});
t = (+new Date()) - t;
console.log(t);
```

It returns something between 2000-3000 ms.

**Comment by eggplantzzz** [comment]
Hey @bgokcol, I'm not really sure I know much about the version of web3 that you are using. Could you try changing the version of web3 you are using to 1.7.1? Some of these versions (like the release candidate version you are using) may have been abandoned...

Let us know if that resolves your issue! If not we'll try and help you troubleshoot further. Thanks!

**Comment by bgokcol** [comment]
Hello @eggplantzzz, I downgraded Web3 to v1.7.1@rc-0 version but sendTransaction process still takes 2-3 seconds. 😐

How can I be sure about that transactions are mined instantly? I'm not sure if problem is in Web3 or Ganache side at the moment.

**Comment by davidmurdoch** [comment]
Is it possible your transaction is slow because you have to interact with the BSC chain? Try setting a hard-coded fork block number and run the code twice. Doing this will make ganache use a persistent cache.


Example:

```
javascript
const options = {
    fork: {
        url: 'https://bsc-dataseed.binance.org',
        blockNumber: 225817323
    },
    miner: {
        blockTime: 0
    }
}
```

**Comment by bgokcol** [comment]
@davidmurdoch Yes, my code interacts with BSC chain. This is probably the reason.

**fork.blockNumber** worked but for second run. On the first run, it took same time as before. So, is there anyway to run first transaction within a few ms? It's not possible as far as I see but I'd be glad if you can suggest me something else for my purpose.

I've a transaction and want to simulate it in 1 second. I need to send it first then I'll use eth_call function.

**Comment by davidmurdoch** [comment]
Only if you sync the whole chain locally first. :-)

**Comment by davidmurdoch** [comment]
Closing this one as I don't think there is a solution possible on Ganache's side.
