### ISSUE TITLE
EIP-1193-compliant providers

### ISSUE THREAD

**Issue by szgyuszi1** [ConsenSys-archive/ganache#2558]
Ganache forking only supports EIP-1193-compliant providers. Legacy support for send is currently enabled, but will be removed in a future version _without_ a breaking change. To remove this warning, switch to an EIP-1193 provider. This error is probably caused by an old version of Web3's HttpProvider (or ganache < v7)

how i can switch to EIP-1193 provider  on terminal?

**Comment by davidmurdoch** [comment]
That message should probably be removed, at least for a few years, as Web3's stable version is not currently an EIP-1193 provider (it was for a brief moment when this code was originally written) and we need to keep compatibility with web3 verisons for a long time.
