### ISSUE TITLE
Feature request: Use a config file to start Ganache with parameters

### ISSUE THREAD

**Issue by MatthieuScarset** [ConsenSys-archive/ganache#2576]
Not sure if this is already available - and not documented - or if it was already requested before.

It would be really helpful to have a configuration file to start Ganache with parameters.

Problem:
- Running Ganache with parameters is a very _long_ command
- ex: `ganache --wallet.seed="I have to copy my seed" --chain.allowUnlimitedContractSize=true  --logging.debug=true ...etc`

Expected behavior:
- create a `ganache.config.js` at a given location
- start Ganache with `--config="../../ganache.config.js" 
- the process would read the config file if it exists and pass parameters to Ganache

Expected commands: 
- `ganache` which reads the file automatically
- or `ganache --config="../../ganache.config.js"` to specifiy a file at a given location

Note: there already is this option for "Truffle" with `truffle-config.js`

**Comment by davidmurdoch** [comment]
Closing as duplicate of https://github.com/trufflesuite/ganache/issues/2102 (or more specifically: https://github.com/trufflesuite/ganache/pull/811). Head over to those issues and give it a "thumbs up" to help further inform our priorities! You can also hit the Subscribe button on those issues to be notified of future updates. Thanks!
