### ISSUE TITLE
Incoherent "Address already in use 127.0.0.1:XXXX" issue when using Ganache programmatically (JS)

### ISSUE THREAD

**Issue by MatthieuScarset** [ConsenSys-archive/ganache#2580]
I'm having an issue with Ganache when trying to use it _programmatically_ with a JavaScript script.

Basically **it doesn't want to start** saying **port is already in use** - whereas it is not :shrug:  

It **does start** with the same port if I run the CLI directly.

How to reproduce: 
- create a script for Ganache (see code below)
- run `node ganache.js` => does not work, results in  "Address already in use 127.0.0.1:XXXX", no matter the port
- run `./node_modules/.bin/ganache -p XXXX` => it works 

Here's the content of the script `ganache.js` - based on the example provided in README:
```JavaScript
require("dotenv").config();
const ganache = require("ganache");
const Web3 = require('web3');

const options = {
  account_keys_path: "ganache.json",
  wallet: {
    accounts: [
      {
        secretKey: `${process.env.PRIVATE_KEY}`,
        balance: Web3.utils.toHex(`${process.env.INITIAL_BALANCE}`)
      }
    ],
  }
};

const port = process.env.PORT || 8545;
const server = ganache.server(options);
server.listen(port, async err => {
  if (err) throw err;
  console.log(`ganache listening on port ${port}...`);
  const provider = server.provider;

  await provider.request({
    method: "eth_accounts",
    params: []
  }).then(accounts => console.log(accounts));

});
```

**Comment by davidmurdoch** [comment]
Can you try casting the env port to a number?

Also, what version of node and what operating system?

**Comment by MatthieuScarset** [comment]
Good catch! thank you, it seems that the issue was to cast to env 

Apparently, `parseInt(process.env.PORT)` fixes the issues. 

I've tried several different start/stop with different values and now Ganache "restart" correctly.

Thank you for your help!

---

For the record, here's my implementation of Ganache programmatically:
https://github.com/MatthieuScarset/quick-dapp/blob/develop/ganache.js

**Comment by davidmurdoch** [comment]
I'm going to reopen this as this is a very common use case we should probably support out of the box!

**Comment by MatthieuScarset** [comment]
> I'm going to reopen this as this is a very common use case we should probably support out of the box!

let me know if/how I can help

**Comment by amandesai01** [comment]
I am willing to open a PR fixing this. Let me know if needed.

**Comment by jeffsmale90** [comment]
Hi @MatthieuScarset  - I just joined the team and picked up this case as a familiarisation task. Feel free to have a look at the change above - I tested with pretty much your exact snippet and it worked as expected.

**Comment by MatthieuScarset** [comment]
Those changes look good to me - thanks @jeffsmale90 
I guess we can close this issue now 
WAGMI
