### ISSUE TITLE
Support binding to port 0

### ISSUE THREAD

**Issue by BlinkyStitt** [ConsenSys-archive/ganache#2643]
If you ask linux to bind to port 0, it will automatically pick an open port for you. This can be really helpful when running multiple instances of ganache on the same machine. Currently, ganache says `Invalid port number '0'`

Please make ganache support binding to port 0.

It would also be helpful (though not necessary) if it wrote this port to a file somewhere.

**Comment by davidmurdoch** [comment]
uWebSockets, the library we use, does [support this](https://github.com/uNetworking/uWebSockets.js/blob/9b3efbdfa315f4ec559fc8a6afe78083007bb7df/examples/AutomaticPortSelection.js). We just need to provide a way for the user to get this port - we should probably just copy node's API here.

We'll also need to update our [fork of uwebsockets](https://github.com/trufflesuite/uws-js-unofficial) as I don't think the fallback exposes the feature.

Additional context may be found in [this PR comment](https://github.com/trufflesuite/ganache/pull/2610#discussion_r828101288).

Would you like to work this issue?

**Comment by BlinkyStitt** [comment]
You probably don't want me writing any JavaScript haha

**Comment by davidmurdoch** [comment]
Haha. No worries. Do you know of any cli tools that can "bind" to port 0 and then output the actual port to a file?
