### ISSUE TITLE
Chain Id mismatch on development network

### ISSUE THREAD

**Issue by leykun10** [ConsenSys-archive/ganache#2662]
```
CHAIN_ID = block.chainid;
```
initialized in the smart contract, evaluates to 1 on a ganache development network
```
development: {
      host: "127.0.0.1",     // Localhost (default: none)
    port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
    },
```
while  on the same network
```
chainId = await web3.eth.getChainId()
```
evaluates to  1377, causing a chain Id mismatch between off-chain and on-chain.
I am using EIP712 standard to sign signatures which requires chainId to be the same on-chain and off-chain.
This issue arises only on the development network.

**Comment by davidmurdoch** [comment]
What version of ganache?

**Comment by leykun10** [comment]
version
```
6.12.2
```

**Comment by davidmurdoch** [comment]
Please update up v7: https://github.com/trufflesuite/ganache/blob/develop/UPGRADE-GUIDE.md

**Comment by leykun10** [comment]
Working! Awesome I appreciate it!
