### ISSUE TITLE
can't find evm_unlockUnknownAccount 

### ISSUE THREAD

**Issue by Chiray1** [ConsenSys-archive/ganache#2665]
`evm_unlockUnknownAccount : Unlocks any unknown account. Accounts known to the personal namespace and accounts returned by eth_accounts cannot be unlocked using this method; use personal_unlockAccount instead.`

This was supported in ganache-cli to add an account at runtime but I cannot find it anywhere in ganache. Is there something else?

**Comment by davidmurdoch** [comment]
What version of ganache are you using? The `ganache-cli` package is deprecated. Use the `ganache` package instead.

**Comment by Chiray1** [comment]
i am using the ganache v7 but it hasnt the evm_unlockUnknownAccount function which is available in ganache-cli

**Comment by davidmurdoch** [comment]
Ah, sorry. I misunderstood. You should use `evm_addAccount` followed by `personal_unlockAccount` to unlock it.

**Comment by Chiray1** [comment]
I'm trying to add an account where I don't know the key from. If I used evm_addAccount followed by personal_unlockAccount I get an error saying it doesn't know the key.

**Comment by davidmurdoch** [comment]
Are you doing something like the following with Ganache v7.0.3?

```
 await provider.send('evm_addAccount', [address, ""]);
 await provider.send('personal_unlockAccount', [address, ""]); 
 ```

**Comment by Chiray1** [comment]
yes, is that wrong?

**Comment by Chiray1** [comment]
I did do a callback and waited for the response, I just tried with a sleep in between and it seems to work. I'm guessing ganache does some more stuff in the background even after it gives back the response that the account has been added?

**Comment by Chiray1** [comment]
It seems very slow though, I have to do a 200ms sleep. Firing up a new ganache provider and unlocking the address there only takes about 80ms.

**Comment by davidmurdoch** [comment]
It doesn't do anything in the background here. Can you share your code?

**Comment by Chiray1** [comment]
```
await web3.currentProvider.send({
        jsonrpc: '2.0',
        method: 'evm_addAccount',
        params: [address, ''],
        id: new Date().getTime()
      }, (err, result) => {
        console.log(result);
      }) 

await sleep(500);

await web3.currentProvider.send({
        jsonrpc: '2.0',
        method: 'personal_unlockAccount',
        params: [address, ''],
        id: new Date().getTime()
      }, (err, result) => {
        console.log(result);
      })
```

**Comment by davidmurdoch** [comment]
I think the web3 provider lets you either pass a callback _or_ `await`, but not both. So you'll need to do something like:

```javascript
await web3.currentProvider.send({
        jsonrpc: '2.0',
        method: 'evm_addAccount',
        params: [address, ''],
        id: new Date().getTime()
      });

await web3.currentProvider.send({
        jsonrpc: '2.0',
        method: 'personal_unlockAccount',
        params: [address, ''],
        id: new Date().getTime()
      });
```

**Comment by Chiray1** [comment]
I tried this:

```

const ganacheProvider = ganache.provider({"fork": 'http://localhost:8545/', "port": 7545})
await ganacheProvider.send({
        jsonrpc: '2.0',
        method: 'evm_addAccount',
        params: [address, ''],
        id: new Date().getTime()
      })

await sleep(500);

await ganacheProvider.send({
      jsonrpc: '2.0',
      method: 'personal_unlockAccount',
      params: [address, ''],
      id: new Date().getTime()
      })

```
As of web3 1.0, provider.send is no longer synchronous and must be passed a callback as its final argument.

**Comment by Chiray1** [comment]
```
let tx = {
        from: address,
        chainId: 1337,
        to: address,
        value: 1,
        gasLimit: 150000,
        gasPrice:  50000000000,
    }
    let signedTx = await web3.eth.signTransaction(tx, tx.from);
    await web3.eth.sendSignedTransaction(signedTx);
Error: sender account not recognized
let tx = {
        from: address,
        chainId: 1337,
        to: address,
        value: 1,
        gasLimit: 150000,
        gasPrice:  50000000000,
    }

    ganacheProvider.send({
        jsonrpc: '2.0',
        method: 'evm_addAccount',
        params: [address, ''],
        id: new Date().getTime()
      }, (err, result) => {console.log(result);});

      //await sleep(500);

    ganacheProvider.send({
        jsonrpc: '2.0',
        method: 'personal_unlockAccount',
        params: [address, ''],
        id: new Date().getTime()
      }, () => {
      }); 

    await sleep(500);
    let signedTx = await web3.eth.signTransaction(tx, tx.from);
    await web3.eth.sendSignedTransaction(signedTx);
```

I tried this now and I get: Error: authentication needed: passphrase or unlock

**Comment by davidmurdoch** [comment]
You aren't waiting for each command to finish before starting the next one. you need to `await` the calls to `ganacheProvider.send`. Do NOT pass a callback here.

**Comment by Chiray1** [comment]
I need to pass a callback otherwise I get the error that since web3 1.0 a callback is requiered... and the await sleep(500); should have bene enough so that the other commands finish, right?

**Comment by Chiray1** [comment]
do you get it to work?

**Comment by Chiray1** [comment]
also when I unlock the address through the provider options, so wallet: {unlockedAddresses: [address]}
and try to send a transction from the address with

```
let signedTx = await web3.eth.signTransaction(tx, tx.from);
await web3.eth.sendSignedTransaction(signedTx);
```

 I get the error: insufficient funds for gas * price + value
even though eth.getBalance returns 10eth. `web3.eth.signTransaction` doesn't work as it should I think

web3.eth.sendTransaction(tx) works for some reason

**Comment by davidmurdoch** [comment]
You account has enough gas, but the transaction does not. You probably need to pass a valid gas price (or base fee for a type 2 transaction) to `signTransaction`.

I'll close this since the original issue is resolved. Please open another if you find any bugs!
