### ISSUE TITLE
to resolve, close the issue

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache#2700]
to resolve, close the issue

**Comment by Ptahliu** [comment]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/102340608/160232141-a62276d8-aab0-472e-8f50-4a7bcf875e3e.png">

**Comment by davidmurdoch** [comment]
I don't think this has anything to do with "supporting other chains", and more likely that you're Internet connection wasn't working or the node was being flaky (which is usually the case with BSC).

**Comment by Ptahliu** [comment]
> I don't think this has anything to do with "supporting other chains", and more likely that you're Internet connection wasn't working or the node was being flaky (which is usually the case with BSC).

After a variety of tests, it may be as you say the case of the.
