### ISSUE TITLE
Ensure that only hex values are used in hex strings

### ISSUE THREAD

**Issue by MicaiahReid** [ConsenSys-archive/ganache#2725]
Currently `json-rpc-base-types` validates that a string is prefixed with "0x" but not that the actual data is hex data. For example, `"0x a string"` is valid according to the base type.

**Comment by davidmurdoch** [comment]
Note: we plan to throw out all of the current JSON-RPC stuff, because it is trash (except the actual interface since doing things like `Data.from` is rather pleasant)

**Comment by MicaiahReid** [comment]
This TODO and four other similar TODOs on the same file need to be fixed once this is merged:
https://github.com/trufflesuite/ganache/pull/2565/files#diff-7c45b1ed67b5ed69774d3ae2bf54711bd5fd4522eccff16f7e8d6a16f6dd582aR482
