### ISSUE TITLE
Don't allow negative numbers to be used as `Quantity`

### ISSUE THREAD

**Issue by MicaiahReid** [ConsenSys-archive/ganache#2728]
Don't do it!

**Comment by MicaiahReid** [comment]
This TODO and four other similar TODOs on the same file need to be fixed once this is merged: https://github.com/trufflesuite/ganache/pull/2565/files#diff-7c45b1ed67b5ed69774d3ae2bf54711bd5fd4522eccff16f7e8d6a16f6dd582aR484

**Comment by jeffsmale90** [comment]
There's a couple of todos here https://github.com/trufflesuite/ganache/pull/2716 also.
