### ISSUE TITLE
add rate limit logic 

### ISSUE THREAD

**Issue by BlinkyStitt** [ConsenSys-archive/ganache#2736]
While using a free host for testing some scripts, I hit some rate limiting errors. Ganache should make it easy to set rate limits for the forked node.  If I set rate limits in my scripts, they aren't very reliable because sometimes queries to ganache don't hit the remote node at all and I end up rate limiting myself needlessly. I also think that at other times a single query to ganache can generate multiple queries to the forked node.

Letting the client specify X requests per Y seconds should prevent most rate limiting errors from occurring.

If api keys are shared between multiple systems, rate limits could still be hit. Looking at things like x-rate-limit headers are better for that. And building something that automatically responds to HTTP 429 or x-rate-limit headers or similar might work some places, but every provider seems to work a little different. One error I got did not have the HTTP error code that I expected; instead it had a json error of `{'code': -32005, 'message': 'Too Many Requests error received from speedy-nodes-nyc.moralis.io'}` (though the docs say they do set the headers). Because some provider's load balancers give errors in inconsistent ways, any sort of automatic back-off/retry will be difficult to implement.

**Comment by davidmurdoch** [comment]
Have you tried the --fork.requestsPerSecond option?

**Comment by BlinkyStitt** [comment]
Oh. I missed that. Too used to older versions of ganache.

**Comment by davidmurdoch** [comment]
Cool! Let me know if it works for you. Rate limiting is not an exact science, and it's probably that the advertised rate limit applies is accurate over a specific period of time (a sampling "window"), and Ganache's window may not match Moralis's (it was tuned for Infura).

If you do discover issues please let me know, as I am interested in making it compatible with Moralis if the current configuration doesn't work well.

**Comment by BlinkyStitt** [comment]
So far this flag is working for me against moralis. I haven't hit any more rate limits.
