### ISSUE TITLE
Mining a block with an old timestamp only half works

### ISSUE THREAD

**Issue by BlinkyStitt** [ConsenSys-archive/ganache#2791]
I wrote [some code for brownie scripts](https://gist.github.com/WyseNynja/608d522ff68fd06ccc2d9c057ba4c206) that replays an old block locally so that I can use debug_traceTransaction when I only have access to a remote node that does not allow this RPC. In order for this to work, I have to mine the transaction with the old timestamp. This looked like it was working on first glance, but then I noticed my replayed transaction was failing with "revert: DEADLINE". 

When mining a block with an old timestamp, only the timestamp on the block is getting set to the old time; the timestamp on the transactions is the current time. 

```
(Pdb++) chain[-1].timestamp
1627430445
(Pdb++) history[-1].timestamp
1648846471
```

The code that is hitting this problem is not yet open source, but I don't think this will be too hard to reproduce.

Also, my code works with hardhat, but hardhat doesn't have the rate limiting I need so now I'm a bit stuck.

**Comment by davidmurdoch** [comment]
Hm, interesting. Not sure what could be going wrong here. In the meantime can you use ganache forking with `debug_traceTransaction` with the original transaction's hash, or do you have to replay the transaction locally first?

**Comment by davidmurdoch** [comment]
Oh! `ganache` doesn't have `evm_setAutomine`. Instead, you can call `miner_stop` to stop the miner, and `miner_start` to resume auto mining. While the miner is "stopped" you can call `evm_mine` to force the miner to mine momentarily. Can you try that and let me know if it works?

I'm not sure why hardhat used a different name for their miner start/stop RPC method, as miner_stop and miner_start is a geth standard: https://geth.ethereum.org/docs/rpc/ns-miner. Maybe we should alias it in Ganache to prevent confusion. Are you aware of any semantic differences in behavior when in the stopped state?

Is there anything else you find that Ganache is missing that you'd need?

**Comment by WyseNynja** [comment]
I believe that brownie is already doing that to run off auto mining.

**Comment by BlinkyStitt** [comment]
That explains it. I wasn't checking the response for evm_setAutomine.

**Comment by BlinkyStitt** [comment]
> Hm, interesting. Not sure what could be going wrong here. In the meantime can you use ganache forking with `debug_traceTransaction` with the original transaction's hash, or do you have to replay the transaction locally first?

Yeah. That's what I'm going to do instead. That should work faster, too.

EDIT: actually, this seems to be slower. I'm hitting 90 second timeouts on things that worked before

**Comment by davidmurdoch** [comment]
Fetching all the necessary state from the remote node is slow the first time. If you always fork at a specific block number successive runs will be faster, add they'll run from a local cache. Let me know if that helps!
