### ISSUE TITLE
Add tests to check for `eth_call` side effects

### ISSUE THREAD

**Issue by MicaiahReid** [ConsenSys-archive/ganache#2934]
If i'm not \wrong about the above then we don't yet have exhaustive tests that check if `eth_call` has side effects and we should add those.

_Originally posted by @davidmurdoch in https://github.com/trufflesuite/ganache/pull/2565#discussion_r851433168_

**Comment by davidmurdoch** [comment]
We do have a test ("does not create a transaction on the chain" -- which is not a very robust test). The new code introduced in #2565 modifies state directly now, so we need to be extra careful that those state changes don't stick around.

**Comment by davidmurdoch** [comment]
I think we can consider this as implemented in #2565
