### ISSUE TITLE
Fork transaction mining fails randomly: EIP1559FeeMarketTransaction.fillFromResul: revert

### ISSUE THREAD

**Issue by miohtama** [ConsenSys-archive/ganache#3006]
I am running the Ganache fork against Ethereum mainnet. Sometimes transaction mining fails randomly.

```
VM Exception while processing transaction: revert', 'stack': 'RuntimeError: VM Exception while processing transaction: revert\n    at EIP1559FeeMarketTransaction.fillFromResult (/Users/moo/.nvm/versions/node/v16.14.2
```

Full Ganache traceback:
```
{'message': 'VM Exception while processing transaction: revert', 'stack': 'RuntimeError: VM Exception while processing transaction: revert\n    at EIP1559FeeMarketTransaction.fillFromResult (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/1.js:2:178257)\n    at Miner.<anonymous> (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/1.js:2:120564)\n    at async Miner.<anonymous> (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/1.js:2:118896)\n    at async Miner.mine (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/1.js:2:123429)\n    at async Blockchain.mine (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/1.js:2:37593)\n    at async Promise.all (index 0)\n    at async TransactionPool.emit (/Users/moo/.nvm/versions/node/v16.14.2/lib/node_modules/ganache/dist/node/0.js:2:81959)', 'code': -32000, 'name': 'RuntimeError', 'data': {'hash': '0xb1d53acb5dafb89a91bc053e099cd0c496ca09a646009a6f36f82fa075d31741', 'programCounter': 19216, 'result': '0xb1d53acb5dafb89a91bc053e099cd0c496ca09a646009a6f36f82fa075d31741', 'reason': None, 'message': 'revert'}}
```

There are no further revert details like a reason. If I restart Ganache and attempt again there is no error. There also does not seem to be a pattern on which transaction I send, though I could be wrong and I just don't see a pattern yet.

Ganache arguments:

```
 ganache-cli --chain.vmErrorsOnRPCResponse true --server.port 30001 --fork.url http://127.0.0.1:8545 --wallet.unlockedAccounts 0x9696f59E4d72E237BE84fFD425DCaD154Bf96976 --wallet.unlockedAccounts 0x47ac0Fb4F2D84898e4D9E7b4DaB3C24507a6D503 --wallet.unlockedAccounts 0x57757E3D981446D585Af0D9Ae4d7DF6D64647806 --wallet.unlockedAccounts 0x5754284f345afc66a98fbB0a0Afe71e0F007B949 --hardfork london
```

- Ganache version 7.10
- Local Ethereum node (geth)

Not sure if this is an error with my own Ethereum node, Ganache, or something else. I would be grateful for any dianostics tips.

**Comment by MicaiahReid** [comment]
Hi @miohtama, would it be possible to post a transaction that is failing the next time this happens?

**Comment by miohtama** [comment]
Happy to try to create a repeatable example. Will take some time. 

Some other comments  and questions

- This is mostly an issue with long running operations (long delay between transactions)

- The same issue with the public Binance smart chain endpoint

- Would the underlying Ethereum mainnet node receiving new blocks somehow break Ganache fork?

**Comment by davidmurdoch** [comment]
@miohtama 

> Would the underlying Ethereum mainnet node receiving new blocks somehow break Ganache fork?

No, ganache should be unaffected. It might be possible to get some strange bits of state if you fork at the real latest block via `--fork.blockNumber {some block number here}` and that block is reorged later on.

**Comment by davidmurdoch** [comment]
Closing for issue maintenance. If you do create a repeatable example please to update us here!
