### ISSUE TITLE
npm install ganache -g failed | Ubuntu 21.10 | node -v v18.0.0  npm -v 8.8.0

### ISSUE THREAD

**Issue by abstractumx** [ConsenSys-archive/ganache#3019]
Hello @trufflesuite

i am trying to install ganache on ubuntu with the following

```
npm install ganache --global
```
i got this errors:

```
user@ubuntu~$ npm install ganache --global
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/ganache
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ganache'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ganache'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/ganache'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

```

i search online that on linux you have to use:

```
$ sudo npm install ganache --global
```
but for obv reasons, installing npm package with ```sudo``` privileges, is not a best practice
but this means that i change node_module folder parameters/variables and it could be dangerous for security reason. Am I correct? 

---
Machine Config:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

node -v
v18.0.0

npm -v
8.8.0
```
How can i fix this?
Thanks

**Comment by abstractumx** [comment]
I've found out that i can run it using the GUI running the following command:

```
$ chmod +x ganache-2.5.4-linux-x86_64.AppImage
```
but still can't work using cli terminal

**Comment by davidmurdoch** [comment]
Was my [last answer](https://github.com/trufflesuite/ganache/issues/3011#issuecomment-1113730739) to this question not sufficient?

Note: official Node 18 support will be in the next release. Try Node 16.

**Comment by davidmurdoch** [comment]
Ganache GUI and ganache, the command line package, are different things (GUI uses its own ganache cli instance internally based on ganache v6)

**Comment by abstractumx** [comment]
Hi @davidmurdoch, 
Ok I rollback on 16.x 

Can you also please tell me what are the difference between:
```
npm install ganache --global
```
and
```
npm install ganache 
```
docu explains only that is used if someone wants to run into an npm project. There are any other major differences?

Thanks for the support.
AX

**Comment by davidmurdoch** [comment]
Check out https://nodejs.dev/learn/npm-global-or-local-packages for a decent explanation.

**Comment by abstractumx** [comment]
> Check out https://nodejs.dev/learn/npm-global-or-local-packages for a decent explanation.

Ok so basically is functional if I want use that package for all user of just for one installing it locally. Thank you!

**Comment by davidmurdoch** [comment]
No problem. Please feel free to close this issue if it has been solved for you.

**Comment by abstractumx** [comment]
> No problem. Please feel free to close this issue if it has been solved for you.

Yes last question: reading the link you have suggested before I found this:

>_[Installing](https://docs.npmjs.com/cli/install) a package globally allows you to use the code in the package as a set of tools on your local computer._
> 
> To download and install packages globally, on the command line, run the following command:
> ```
> npm install -g <package_name>
> ```

I dont get the point by saying _**to use the code in the package as a set of tools on your local computer.**_
I would like to understand this, just to clarify if for my needs i have to install with -g flag or not! 

Thank you!

**Comment by davidmurdoch** [comment]
You can use ganache from the command line: https://github.com/trufflesuite/ganache#command-line-use or programmatically: https://github.com/trufflesuite/ganache#programmatic-use

I don't know what your needs are, but you probably want to install it globally.
