### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)请求大神解决

### ISSUE THREAD

**Issue by kimpace19882627** [ConsenSys-archive/ganache#3021]
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

Compiling your contracts...
===========================
✓ Fetching solc version list from solc-bin. Attempt #1
✓ Downloading compiler. Attempt #1.
✓ Downloading compiler. Attempt #2.
✖ Downloading compiler. Attempt #3.

**Comment by davidmurdoch** [comment]
What version of node are you on and what operating system?

**Comment by slav-arcadechain** [comment]
The same issue on the following config:
```
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
❯ truffle version
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Truffle v5.5.15 (core: 5.5.15)
Ganache v^7.1.0
Solidity - 0.8.1 (solc-js)
Node v14.19.3
Web3.js v1.5.3
```

**Comment by davidmurdoch** [comment]
This should be fixed by #3208 in the next release

**Comment by kkggg55** [comment]
I'm facing the same bug. Any fix coming soon?

**Comment by davidmurdoch** [comment]
@KhalilJouaneh please open a new issue and provide details.
