### ISSUE TITLE
ganache installation problem

### ISSUE THREAD

**Issue by 0xvanbeethoven** [ConsenSys-archive/ganache#3035]
Ganache won't run, after installing the newest version. Error message:
zsh: abort      ganache

**Comment by davidmurdoch** [comment]
What os? What node version? What npm version? What command are you running?

**Comment by 0xvanbeethoven** [comment]
Ganache 8.9.0 on Mac Montery 12.3.1 (M1) simply running ganache

**Comment by 0xvanbeethoven** [comment]
<img width="1440" alt="Capture d’écran 2022-05-05 à 18 53 38" src="https://user-images.githubusercontent.com/103021596/167045097-28a8d62e-94e5-4837-8daa-cb540cb41bc2.png">

**Comment by 0xvanbeethoven** [comment]
<img width="1440" alt="Capture d’écran 2022-05-05 à 18 54 15" src="https://user-images.githubusercontent.com/103021596/167045156-3d53ea74-0fc1-468e-9c8e-34c71ade9368.png">

**Comment by davidmurdoch** [comment]
Ganache 8.9.0 isn't a thing, that's the npm version. It looks like you might be running npm 8.9.0 on node 12. Can you try node 14 or node 16?

**Comment by 0xvanbeethoven** [comment]
Yes, I must say I am very new to testing and using ganache, how would I go about doing that.

**Comment by 0xvanbeethoven** [comment]
Ooh I think I fixed it thanks so much
