### ISSUE TITLE
docker image with custom chainId

### ISSUE THREAD

**Issue by success-0627** [ConsenSys-archive/ganache#3061]
![image](https://user-images.githubusercontent.com/53897531/168335025-9e070671-38dd-403a-9d4b-c54001591c21.png)

![image](https://user-images.githubusercontent.com/53897531/168335074-4af3314e-aa37-4775-9d2e-72cf974c7cc3.png)

If I remove `- "--chain.chainId 56"` / `- --chain.chainId 56` / `- "--chain.chainId=56"`, everything is ok.

**Comment by success-0627** [comment]
PS: this is what I tried inside of my custom docker composer.
![image](https://user-images.githubusercontent.com/53897531/168335382-5e5b3816-12bc-4dab-a298-a11e3d953f34.png)

**Comment by davidmurdoch** [comment]
I don't think that is how use the docker compose `command` option. See their docs here: https://docs.docker.com/compose/compose-file/compose-file-v3/#command

**Comment by success-0627** [comment]
I tried with that too. same error

**Comment by davidmurdoch** [comment]
I don't know much about docker, so i'm afraid I won't be able to help. I'll go ahead and convert this issue to a discussion.
