### ISSUE TITLE
No longer able to access state trie

### ISSUE THREAD

**Issue by area** [ConsenSys-archive/ganache#3076]
I am working on a long-overdue upgrade to the latest ganache at [Colony](https://github.com/joincolony/colonynetwork), and believe I've hit a blocker now that that the internals of the provider are no longer accessible. We have [smoke tests](https://github.com/JoinColony/colonyNetwork/blob/develop/test-smoke/colony-storage-consistent.js#L67) that alert us if the state trie hash associated with a contract after the tests have been run has changed. The worst-case scenario that this would alert us to is the storage layout changing unexpectedly, but normally it's a change associated with the addition of a variable during an upgrade, or the address of a deployed contract that is stored changing due to the number of transactions the deploying address makes changing.

Getting the state hash for an address captures the entire storage layout, avoiding the need to check every slot that we think should be set - but even this wouldn't capture the change of a storage slot we weren't expecting to be set.

An interface making this possible, or a workaround, would be greatly appreciated! Note that read-only access (in this case) would be adequate.

**Comment by davidmurdoch** [comment]
I think we can accommodate fairly quickly and easily! Can you share the original code that used Ganache's internals?

**Comment by area** [comment]
We'd obviously be happy with any way to access this, but as it stands this is what we're using:

```
    web3.currentProvider.engine.manager.state.blockchain.stateTrie.get(utils.toBuffer(address), (err, res) => {
        if (err !== null) return reject(err);
        return resolve(res.toString("hex"));
      });
```

where the provider came from `ganache.provider`

**Comment by davidmurdoch** [comment]
Thanks @area, do you think any of geth's existing debug methods would do the trick? If we implemented  https://geth.ethereum.org/docs/rpc/ns-debug#debug_getmodifiedaccountsbyhash do you think that would solve the problem?

**Comment by area** [comment]
I don't think so. The pattern we're using is that we know what the storage hash we expect is, which is saved in the test itself, and want to compare the storage hash at the end of the series of tests with that hash. We expect the storage hash for an address to change as blocks are mined as the tests are run, as the contracts are used. As far as I can tell, that method would just return the addresses that had their storage hash change in the specified block range - not the storage hashes themselves.

Having read through the geth debug methods, I don't think any of these give direct access to what we're after.

**Comment by davidmurdoch** [comment]
@area sorry we haven't gotten to this yet. Would your be able to use the `storageHash` property of `eth_getProof` if we added support for it?

It returns the account's `stateRoot`: https://github.com/ethereumjs/ethereumjs-monorepo/blob/3e4e7bed681bfa6d1c95abbcc28f6508e828339d/packages/vm/src/state/stateManager.ts#L338

**Comment by area** [comment]
I believe that would be sufficient for us, yes.

**Comment by davidmurdoch** [comment]
@MicaiahReid want to tackle eth_getProof next?

**Comment by davidmurdoch** [comment]
@area we plan on releasing this next Tuesday or Wednesday! You'll need to update the hardcoded state root values in your smoke tests, as Ganache v7 uses a `merkle-patricia-tree`'s `SecureTrie` (the keys are hashed before insertion) whereas Ganache v6 did not.

Just to be absolutely sure this would be a viable solution for you @jeffsmale90 created a local build of Ganache v7 that used `merkle-patricia-tree`'s `CheckPointTrie` to mimic the behavior of older ganache versions and then ran Colony's smoke tests. The tests passed.

One way to update your tests is to update `getAddressStateHash` as follows:

```javascript
function getAddressStateHash(address) {
  return new Promise((resolve, reject) => {
    web3.currentProvider.request({method: "eth_getProof", params: [address, [], "latest"]}).then(result => {
      return resolve({ stateRoot: Buffer.from(result.storageHash.slice(2), "hex") });
    }).catch(e => {
      reject(e);
    })
  });
}
```
  
and then replace the calls to `new Account()` with direct assignment, e.g.,:
  
```javascript
const colonyStateHash = await getAddressStateHash(colony.address);
const colonyAccount = colonyStateHash; // instead of new Account(colonyStateHash);
```

Let us know if you have any more trouble updating to v7!

**Comment by area** [comment]
The new release has resolved this for us, thanks very much.
