### ISSUE TITLE
cannot fork from okc

### ISSUE THREAD

**Issue by kl456123** [ConsenSys-archive/ganache#3140]
```
ganache --fork https://exchainrpc.okex.org/
```

but some error happended
```
Error: Could not find "earliest" block.
```
then I use hardhat instead
```
yarn hardhat node --fork https://exchainrpc.okex.org/
```
it runs well

**Comment by davidmurdoch** [comment]
Looks like OKC is blocked in the United States, so testing this will be difficult for me. However, if a chain doesn't have an "earliest" block it is absolutely not an Ethereum compatible chain. So I imagine there are many other inconsistencies as well.

You can probably disable Ganache's cache with `--fork.disableCache` to work around this issue for now.

**Comment by kl456123** [comment]
Thanks, it works!

**Comment by davidmurdoch** [comment]
Keeping this open so we can address this.

**Comment by ilovers** [comment]
This issue has been fixed by the okc community. Now it works fine with ganache.

**Comment by davidmurdoch** [comment]
Thanks @ilovers for the update. I originally kept this open because we could fall back to querying for block `0` if `"earliest"` doesn't exist. But since this is such an unlikely issue I think it is okay to close this as "won't fix".
