### ISSUE TITLE
add "finalized" block tag

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#3204]

**Comment by molichio** [comment]
this would be handy right now for some merge preparation testing ☺️

**Comment by davidmurdoch** [comment]
`finalized` and `safe` will be aliases for "latest"

**Comment by manav2401** [comment]
Hi, I would like to consume the "finalized" and "safe" tags for `eth_blockByNumber` api. Is there any way I can do so at this moment with ganache? Also, as a workaround, it would work for me even if returns the latest block when we're calling "finalized" or "safe". Thanks!

@davidmurdoch

**Comment by davidmurdoch** [comment]
@manav2401 you can't use them yet, but soon. We are actively working on it. See https://github.com/trufflesuite/ganache/pull/3658 It will return "latest", for requests for "finalized"/"safe".

**Comment by manav2401** [comment]
@davidmurdoch Thanks a lot for the info. Yes, I was following that PR. Could you help me pointing to some steps/docs using which I can build ganache from source (in this case from your specific branch)?

**Comment by davidmurdoch** [comment]
Clone the repo, checkout the branch, run `npm i`, and then run `npm start -- <you can put your options here>`. Example one liner to do all that: 
`git clone https://github.com/trufflesuite/ganache.git && cd ganache && git checkout merge-things && npm i && npm start -- --fork mainnet --totalAccounts 5`.

Also see https://github.com/trufflesuite/ganache/blob/develop/CONTRIBUTING.md

**Comment by MicaiahReid** [comment]
Closed by #3971
