### ISSUE TITLE
-H SERVER CRASHING

### ISSUE THREAD

**Issue by CryptoWizardsNet** [ConsenSys-archive/ganache#3207]
Hi team,

ganache --fork.url https://bsc-dataseed1.defibit.io -p 8545 -h <MY PRIVATE IP>

when running the command the above command, everything works fine. Until I close and reopen ganache a number of times via cron (every 15 mins). Then everything crashes and repeats transactions like what is showing on the attached. I have tried:

1. killing all ganache processes
2. uninstalling and reinstalling node
3. uninstalling and reinstalling ganache

Whenever I run the -h in the CLI, changing the server host, it for some reasons still shows a rapid amount of transactions happening before my eyes. The only way I have been able to sort this, is by stopping and restarting my Ubuntu AWS instance completely (thus changing the public IP).

PS - If I remove the -h with private IP, everything works fine again.

What are your thoughts on this?

Also to mention, the account balance goes very quickly to zero.

Regards,
Shaun

![issue](https://user-images.githubusercontent.com/96389231/172898148-4612b0f5-234f-45d9-88cf-ae09a9a5215a.png)

**Comment by davidmurdoch** [comment]
Can you copy+paste all the output instead of a screenshot?

**Comment by cliffoo** [comment]
Closing for Issue Maintenance.
