### ISSUE TITLE
implement `cleanupDirectory` function

### ISSUE THREAD

**Issue by MicaiahReid** [ConsenSys-archive/ganache#3662]
When a database is instantiated, the current function to cleanup the database directory is a no-op. We should fix that. 

https://github.com/trufflesuite/ganache/blob/9980cb5513db6f810625783cae325a937587ebb4/src/chains/ethereum/ethereum/src/database.ts#L19

**Comment by davidmurdoch** [comment]
Not always: https://github.com/trufflesuite/ganache/blob/9980cb5513db6f810625783cae325a937587ebb4/src/chains/ethereum/ethereum/src/database.ts#L66

**Comment by MicaiahReid** [comment]
:man_facepalming: my miss!
