### ISSUE TITLE
Can Ganesh be used as a commercial project?

### ISSUE THREAD

**Issue by teymourian** [ConsenSys-archive/ganache#3779]
Hi friends
Can this project be commercialized as a blockchain?
used to have all the features including security and NFT sales
If not, what project should we use?
Thanks

**Comment by jeffsmale90** [comment]
Definitely not. Ganache is designed to _simulate_ a blockchain. As such, it doesn't include the consensus mechanisms from which blockchains derive their security and trust.

**Comment by gnidan** [comment]
you might consider using the Ethereum blockchain for commercial use

**Comment by teymourian** [comment]
tnk @jeffsmale90 @gnidan
