### ISSUE TITLE
`eth_getBlockByNumber` returns block header with non-zero difficulty

### ISSUE THREAD

**Issue by yehted** [ConsenSys-archive/ganache#3851]
By default, the `--miner.difficulty` option is set to `0x1`. After the merge, shouldn't it be `0x0` by default? This is causing problems if someone uses, for example, the [ethereumjs/block](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/block) package, method `Block.fromRPC(...)`, where it expects the difficulty to be zero.

**Comment by davidmurdoch** [comment]
Are you using `ganache@alpha`

**Comment by yehted** [comment]
I'm using v7.4.4

**Comment by davidmurdoch** [comment]
The stable/latest releases don't yet support the merge. You can track progress on it here: https://github.com/trufflesuite/ganache/issues/3693#issuecomment-1284540912

In the meantime you can use https://github.com/trufflesuite/ganache/releases/tag/v7.4.4-alpha.0 if you need merge hardfork logic.
