### ISSUE TITLE
Support Paris hardfork

### ISSUE THREAD

**Issue by robmcl4** [ConsenSys-archive/ganache#3864]
## Current Situation
`ganache` only supports up to the `grayGlacier` ethereum hardfork (see [`src/chains/ethereum/options/src/chain-options.ts:5`](https://github.com/trufflesuite/ganache/blob/cc84f3f28da2710774936b3cf6b4a218d0a5b5ed/src/chains/ethereum/options/src/chain-options.ts#L5)).

However, the [Paris](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md) hardfork (aka 'The Merge') has been active for several weeks now.
Critically, this makes for odd behavior regarding [EIP-4399 "Supplant DIFFICULTY opcode with PREVRANDAO"](https://eips.ethereum.org/EIPS/eip-4399).

## Proposal

I propose the following changes.

1. All blocks produced by `ganache` set the `prevRandao` header field to `0b100...00`, with an option in `evm_mine` to set the value manually. The first bit is set to `1` so that EVM applications may test for Paris hardfork activation by checking that the `PREVRANDAO` value is greater than `2**64`, as suggested in EIP-4399 (ctrl+f "The probability of RANDAO value").
2. Update the `@ethereumjs/vm` dependency to support `Block.prevRandao`, and update all invocations of the EVM to use the `prevRandao` value as appropriate, if the Paris hardfork is active. Note that this will require a major version bump from v5 to v6 -- I am not sure how much work this would be.

Caveat: although `@ethereumjs/evm` does advertise support for EIP-4399, it is currently marked as experimental (see their [README](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/evm/README.md))

**Comment by davidmurdoch** [comment]
We do have a release for support under the alpha tag: https://github.com/trufflesuite/ganache/releases/tag/v7.4.4-alpha.0

You can track our progress getting it to stable here: https://github.com/trufflesuite/ganache/issues/3693#issuecomment-1284540912
