### ISSUE TITLE
Ganache default port 7545, or 8545?

### ISSUE THREAD

**Issue by cilphex** [ConsenSys-archive/ganache#4015]
I've recently started ethereum/solidity programming and I'm using Ganache to run the local blockchain.

When I start up a quickstart workspace in Ganache, by default I see that it is set to port `7545`. However, if you search Google for "Ganache default port", it says that it's `8545`. `8545` would seem to be the expectation of other projects as well, such as the [wagmi](https://github.com/wagmi-dev/wagmi) localhost [chain descriptor](https://github.com/wagmi-dev/references/blob/main/packages/chains/src/localhost.ts).

Why does my local copy of Ganache have a default port of 7545? Has it recently changed?

**Comment by davidmurdoch** [comment]
Ganache UI has a default of 7545. Ganache, the npm package, has a default of 8545.
