### ISSUE TITLE
How to access admin site of ganache? 

### ISSUE THREAD

**Issue by pzg250** [ConsenSys-archive/ganache#4062]
After install ganache docker image and run, I can see it runs on 8545 port. 
It will shows 404 error when I tried to access it by browser. (localhost:8545)

Anyone can help? thx

**Comment by davidmurdoch** [comment]
The docker image doesn't have a UI to access. It is a node simulator only. We may add that feature in the future.

**Comment by pzg250** [comment]
thanks
