### ISSUE TITLE
eth_getTransactionCount pending does not take into account tx in the local mempool

### ISSUE THREAD

**Issue by mprakhov17** [ConsenSys-archive/ganache#4556]
Repro steps:
1. Configure ganache with blockTime = 300
2. Write tx
3. Check `eth_getTransactionCount` with `pending` and `latest` param before the block will be minted

Expected: 
`eth_getTransactionCount` `pending` return `latest` + 1 (tx count in the local mempool). `pending` > `latest`

Actual:
`eth_getTransactionCount` `pending` and `latest` returns the same amount

**Comment by MadelineMurray** [comment]
hi @mprakhov17  - Truffle and Ganache are being sunset. For more information and migration options, click [here](https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat?utm_source=github&utm_medium=referral&utm_campaign=2023_Sep_truffle-sunset-2023_announcement_).
