### ISSUE TITLE
Add support for eth_call state-overrides

### ISSUE THREAD

**Issue by fabioberger** [ConsenSys-archive/ganache#554]
Geth has support for [performing state-overrides](https://geth.ethereum.org/docs/rpc/ns-eth#3-object---state-override-set) when doing an `eth_call`. It would be great if Ganache could support this same behavior.

**Comment by gnidan** [comment]
We'll need to look into what Geth does, but this sounds neat! Thanks for suggesting it!

**Comment by emilianobonassi** [comment]
+1
