### ISSUE TITLE
published ganache bundle is very large

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#744]
we ship separate both cli and a core in one package, but cli should just use the bundled core as is.

The browser bundle is also a bit chunky, should this be shipped as a separate package? Or could we somehow make it use core (probably not, since it needs to polyfill many things)?

**Comment by honestbonsai** [comment]
https://linuxize.com/post/how-get-size-of-file-directory-linux/

Use `sudo du -shc /<folder name>/*`

**Comment by honestbonsai** [comment]
# Notes 

develop is default branch
uses npm

uses ttsc NOT tsc, does transformations for you
npm run build, triggers webpack process
will try to build it even if its not compiled, always run tsc before running build
  ts-loader doesnt pick up all the rules from tsconfig
  if its not already compiled, then it will try to compile, but it will do it wrong
there are no tests for the build output, can write them if u want

mostly working here
https://github.com/trufflesuite/ganache-core/tree/develop/src/packages/ganache, thats where the webpack is, pretty much the only job of this package

webpack.common is where the bulk of the logic is
webpack.node is just core itself
webpack.cli is for cli

CORE
.node is native modules
ganache.min.js 3.2MB
35MB total

CLI
is almost exactly the same, pretty much the same code, but CLI is just a thin wrapper over core
but we are including an extra 30 MB when we publish
cli should just import the node one

// Check sizes of dist folders
du -shc dist/*

to check things are working after the slimming 
======
CLI down:
`node ./src/packages/ganache/dist/cli/ganache.min.js`

NODE, in root test.js
```
const ganache = require("./src/paackages/ganache/dist/node/ganache.min.js")
console.log(ganache) // {server: ..., provider: ...}
```

WEB
npm run build, will rebuild the docs
npm run docs.preview
run it in the browser, see if it works, debug trace transactions
```
const accounts = await provider.request({ method: "eth_accounts", params: []})
console.log(accounts)
```

**Comment by honestbonsai** [comment]
https://linuxize.com/post/how-get-size-of-file-directory-linux/

Size of `dist` directory
`du -shc ./dist/*`

**Comment by davidmurdoch** [comment]
It is much smaller now. Always room for improvement. But good enough to close!
