### ISSUE TITLE
Create docker bundle for cli

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#746]

**Comment by kevinbluer** [comment]
Initial pass of `Dockerfile` at 3675544e199287b8c7a37f0c6e8d5385841b2be3, which is published (for testing) to Docker Hub at the following: https://hub.docker.com/repository/docker/trufflesuite/ganache-core. Note that this will be rolled into `ganache-cli` when upon launch.

**Comment by davidmurdoch** [comment]
@kevinbluer can you make a PR for this?

**Comment by kevinbluer** [comment]
For sure 👌

**Comment by davidmurdoch** [comment]
closed by #746
