### ISSUE TITLE
Ganache 7 CLI doesn't respond correctly to Ctrl+C

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys-archive/ganache#773]
When running Ganache 7's CLI, `Ctrl+C` doesn't work until after `Ctrl-D` is pressed (or put differently, I could only use `Ctrl+D` to reliably close the application). 

I dug into this a bit and added some logging to the top of CLI's `closehandler` method. Looks like the first press of `Ctrl+C` changes the server status from `1` to `4`, but does not completely shut down the process. 

![image](https://user-images.githubusercontent.com/92629/107081531-b0e61480-67a7-11eb-8c45-15ce788bfe4e.png)

To reproduce: 

1. Run the command line via `npm start` or the latest npm release (`npm install -g ganache@internal` then `ganache`)
2. Wait for server to completely start
3. Press `Ctrl+C`. Notice that the application doesn't close. You can press it any number of times and there doesn't seem to be any effect. 
4. Press `Ctrl+D`. At this point I received two behaviors. Either the process would immediately exit, or it would print a new line, after which `Ctrl+C` would work correctly. 

Note that in these reproduction steps I had not sent a request to the server. Also, this appears to be chain agnostic, as the same behavior occurs when specifying the `filecoin` flavor as well (when used in the proper branch).

**Comment by davidmurdoch** [comment]
Fixed in develop
