### ISSUE TITLE
Running `npm install` on Windows makes a handful of changes to source controlled files

### ISSUE THREAD

**Issue by mikeseese** [ConsenSys-archive/ganache#775]
Running `npm install` (and really `npm run postinstall` is where it happens) calls `link-ts-references.ts` and on Windows, `path.join` in that script rewrites all the `tsconfig.json` files with `\\` instead of `/` causing several changes in my working tree:

![image](https://user-images.githubusercontent.com/549323/107090737-826f3600-67b5-11eb-9675-daa4431f7776.png)

This doesn't really affect me since I work mostly in WSL, but I can see someone potentially accidentally committing these changes.

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache-core/commit/517795846cac9cf1ce14ff4855ae9457ea6f3f59
