### ISSUE TITLE
Information about v7 changes

### ISSUE THREAD

**Issue by eggplantzzz** [ConsenSys-archive/ganache#780]
This issue is a placeholder to provide a spot to add information concerning upgrading to Ganache v7. This will include information about breaking changes.

**Comment by diwu1989** [comment]
The draft seem to be here:
https://github.com/trufflesuite/ganache/issues/1337

**Comment by davidmurdoch** [comment]
Thanks @diwu1989 I've updated the URL shortener to point to the right place now
