### ISSUE TITLE
Fix seed randomization

### ISSUE THREAD

**Issue by mikeseese** [ConsenSys-archive/ganache#831]

**Comment by davidmurdoch** [comment]
Is this related to my PR, https://github.com/trufflesuite/ganache-core/pull/816 ? :-D

**Comment by mikeseese** [comment]
It appears that the `wallet-options.ts` changes may also fix this for me (especially since I just copied the logic over from ethereum's lol). Is your observed behavior that the seed is always the same random string?

**Comment by davidmurdoch** [comment]
Yup! The types are wrong, so I used the library wrong.

**Comment by mikeseese** [comment]
Cool, is #816 ready for review?

**Comment by davidmurdoch** [comment]
@seesemichaelj yes, it is
