### ISSUE TITLE
Opinions on how to resolve slowness when forking mainnet

### ISSUE THREAD

**Issue by vasapower** [ConsenSys-archive/ganache#852]
I consider the Ganache `fork` option not just a software feature, but an extremely-strategic key for the mass-adoption of the Ethereum ecosystem.

But I always had a lot of issues caused by slowness when using it, even if I have a full node running locally. So I recently created a very simple utility to [pack and run a forked Ganache instance directly in a browser](https://github.com/b-u-i-d-l/ganache-browser), to bypass any kind of problem related to connection speed.

Doing so I had the possibility to analyze the network traffic through the specific Chrome Console tab and I noticed that maybe the bottleneck can be the massive use of the `eth_getStorageAt` call to query the full node (in order to grab the state of an already-existing contract for the first time I suppose), as you can see in the attached image
![ganache](https://user-images.githubusercontent.com/5588727/110335031-b7281480-8023-11eb-8f65-fc66c585ca26.png)
.

While I perfectly understand that a massive use in a "semi-brute force" way of this call is necessary, 
I was just wondering if it was possible to bypass the sequential mechanism of using that call and switch to some sort of a cumulative bunch of parallel asynchronous calls, mitigated by a mutex approach.

E.G.

```
//First of all, save address dumping status to avoid multiple calls for same address
var alreadyDumping = {};
function dumpContractStorage(contractToDumpAddress) {
    //Retrieve the already existing Promise for the address in input or create a brand new one and cache it
    return alreadyDumping[contractToDumpAddress] = alreadyDumping[contractToDumpAddress] || new Promise(async function(ok) {
        var lastStateVarDumped = 0;
        var varDumpingSteps = 50;
        //kind of save for all contract storage vars before dump in ganache db
        var contractStatusList = [];
        var currentStatusListCall = [];
        //loop to fetch storage vars for the first time and until the contract storage var dump reaches end (the value of all the vars retrieved in the last loop step is 0)
        while(currentStatusListCall.length === 0 || currentStatusListCall.filter(it => it.value === '0x0').length === currentStatusListCall.length) {
			currentStatusListCall = [];
			var end = lastStateVarDumped + varDumpingSteps;
			for(var i = lastStateVarDumped; i < end; i++) {
				currentStatusListCall.push(fetch(forkedNodeAddress) /*... insert correct logic for the AJAX JSONRPC POST call for the eth_getStorageAt method, using contractToDumpAddress to identify the contract and the i value as storage index*/);
			}
			//wait for all the remote calls to end and then dump populated vars in the contractStatusList, in order to save them in the Ganache local DB at the end of computation
			contractStatusList.push(... (currentStatusListCall = await Promise.all(currentStatusListCall)));
			
			//update the lastStateVarDumped for the next loop step
			lastStateVarDumped = end;
		}
		//Save contract dump vars in the ganache DB
		ganacheDB.dump(contractToDumpAddress, currentStatusListCall);
		
		//Terminate the promise
		ok();
    });
}
```

Can this be a useful and viable solution? 

If yes, can you tell me which bunch of project files to edit, in order to prepare a pull request?

Many thanks.

**Comment by davidmurdoch** [comment]
@vasapower ganache is actually fetching storage on-the-fly, and only as needed. It isn't brute-forcing over storage sequentially; which isn't practically feasible, as storage locations are arbitrary. While we could speculate as to the position of storage in many cases, in many other cases we'd be wrong, and this would just cause a slow down. There _is_ a `debug_` RPC method to somewhat solve this, `debug_storageRangeAt`, but it isn't exposed by any (popular) public nodes, so we can't really make use of it.

What we can and will do is cache this data _to disk_ (and in the browser version, to IndexedDB), so the performance penalty is a one-time thing. In the future we'll likely make use of the Ethereum infrastructure we have here at Consensys to _speculatively_ download storage ranges as large binary blobs to improve start up for ganache tests that interact with popular mainnet/testnet contracts/state... but this feature is quite a ways off.

**Comment by vasapower** [comment]
@davidmurdoch Thanks for the response. With "semi-brute force" check I mean the same technique described in this [medium post](https://medium.com/aigang-network/how-to-read-ethereum-contract-storage-44252c8af925) I read several months ago (I'm talking about the `for (index = 0; index < 10; index++){` loop located in the second block of code within the article). 
It would be very informative and interesting for me to understand how you solved this problem, can you tell me where I can find it in the code, please?

Also, many thanks for telling me about the `debug_storageRangeAt` call, it can be extremely useful!
Maybe I can prepare a public, opensource fork of the Ganache code including this as an option flag for those nodes to fork that supports and exposes it, then open a PR here.
I would like to work on it!

Is there any way I can use to easily locate the project files where the `fork` business logic is coded? I just want to avoid spending time searching the entire code base for it.

**Comment by davidmurdoch** [comment]
From that medium post,

> All parameters in the storage are indexed from the beginning.

This bit isn't true in more complex contracts, which are contracts that are likely to see the performance issues we're trying to solve. _Maybe_ this technique could save some time, but I'd have to see some real-world performance benchmarks against some of the popular contracts (like Uniswap) to be convinced. :-)

I'm working on rewriting our forking as we speak, and don't have the code available to share with you right now.

> Maybe I can prepare a public, opensource fork of the Ganache code including this as an option flag for those nodes to fork that supports and exposes it, then open a PR here.

Check back in a month or so if you want to look into contributing to this effort.

**Comment by davidmurdoch** [comment]
It's been much longer than a month, but forking is now 30x+ faster in the latest ganache@7.0.0-beta.2 release than it was before, so I'm going to go ahead and close this issue as I we already implement most of the caching suggestions posted here. Thanks!
