### ISSUE TITLE
Berlin hardfork support

### ISSUE THREAD

**Issue by KaiRo-at** [ConsenSys-archive/ganache#858]
I like the fact that with tests running against ganache, I can run the same EVM code I deploy on Ethereum testnets and mainnet and that I get the same gas usage numbers so I can accurately estimate what gas usage on live setups will be.

The Berlin hardfork does change gas consumption numbers once again but right now I can not set ganache to give me those, istanbul/muirGlacier is the newest set currently supported. See EIPs in https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md for what Berlin changes.

Please add berlin support to ganache, I will be a very happy camper once that happens! :)

**Comment by davidmurdoch** [comment]
Thanks, we'll track this in https://github.com/trufflesuite/ganache-cli/issues/821
