### ISSUE TITLE
fix interactive documentation examples for personal namespace

### ISSUE THREAD

**Issue by eshaben** [ConsenSys-archive/ganache#863]
The following problems exist within the `personal` namespace of the interactive docs:
- `personal_newAccount` example isn't working
- `personal_unlockAccount` example doesn't work because it relies on `personal_newAccount`
- `personal_sendTransaction` example doesn't work because it relies on `personal_newAccount`

The problem is due to the `crypto-browserify` package not being completely compatible with nodes `crypto` module. In `personal_newAccount`, [encrypt](https://github.com/trufflesuite/ganache-core/blob/develop/src/chains/ethereum/ethereum/src/api.ts#L1957) is called and then we begin to run into errors with [scrypt](https://github.com/trufflesuite/ganache-core/blob/develop/src/chains/ethereum/ethereum/src/wallet.ts#L280).

Could try setting up our own provider (like `ganache.provider`) and passing in own accounts. Or could try to polyfill the functions we need from the `crypto` package. Maybe try installing an `scrypt` browser-capable version, or using subtle crypto to `.encrypt` and `.decrypt` which uses the right `aes` type and so we could probably make it work somehow.

References:
- [Crypto - Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/Crypto)
- [SubtleCrypto - Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto)
- [JavaScript implementation of scrypt](https://github.com/ricmoo/scrypt-js)
- [A WebCrypto Polyfill for NodeJS](https://github.com/PeculiarVentures/webcrypto) - This is not suitable for production and shouldn't be used but is relevant to the issue

**Comment by davidmurdoch** [comment]
@MicaiahReid do you remember if this one is complete? If so, can you close?
