### ISSUE TITLE
eth_sendRawTransaction interactive docs example needs a signed transaction

### ISSUE THREAD

**Issue by eshaben** [ConsenSys-archive/ganache#864]
In order to send a raw transaction we need to be able to sign and serialize the transaction, which is easily done using the `ethereumjs-tx` package. However, for the interactive documentation examples we don't currently have a solution implemented for examples that require `import`s of other packages. Need to find a solution for signing and serializing the transaction within the example. Right now `eth_sendRawTransaction` returns an empty object which is not correct.

**Comment by davidmurdoch** [comment]
@MicaiahReid do you remember if this one is complete? If so, can you close?
