### ISSUE TITLE
eth_estimateGas interactive docs example doesn't return anything

### ISSUE THREAD

**Issue by eshaben** [ConsenSys-archive/ganache#865]
the interactive docs example for `eth_estimateGas` doesn't return anything as it is, if you add `gas` of "0xb5" to the tx object an empty object is returned. Either way it's broken as of right now... @davidmurdoch indicated that it's probably because we need to use `toArrayLike(Buffer)` in one place.

**Comment by davidmurdoch** [comment]
@MicaiahReid do you remember if this one is complete? If so, can you close?
