### ISSUE TITLE
Filecoin Deal optimization in database

### ISSUE THREAD

**Issue by mikeseese** [ConsenSys-archive/ganache#868]
Below is a TODO for the Filecoin flavor's DealInfoManager (`src/chains/filecoin/filecoin/src/data-managers/deal-info-manager.ts`). The general issue is that things could be memory and CPU resource intensive and made a bit more efficient with the below changes (or some variation of them).

> This loads all Deal CIDs and then all the
> deals themselves into memory. The downstream consumers
> of this manager then filters them at every time it's used
> (i.e. filters them by DealInfo.State).
> 
> We'll need to rework this in the future. LevelDB has a
> `createReadStream` method that could help with some of this;
> but David M. thinks we'll also need to add another sublevel
> that acts as an index for deal states.

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
