### ISSUE TITLE
Filecoin Private Key Manager performance optimization

### ISSUE THREAD

**Issue by mikeseese** [ConsenSys-archive/ganache#875]
The filecoin flavor's private key manager stores all of the addresses in which it has a private key for in an array as a "hack" to implementing a more efficient indexing method. There is a TODO in `src/chains/filecoin/filecoin/src/data-managers/private-key-manater.ts` that corresponds to this issue

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
