### ISSUE TITLE
Filecoin account persistence performance

### ISSUE THREAD

**Issue by mikeseese** [ConsenSys-archive/ganache#876]
The filecoin flavor's implementation of the `AccountManager` has a `putAccount` that is called whenver an account is changed (balance, nonce, added private key). I'm not sure of the performance implications here, but it likely has room for improvement for high throughput scenarios

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.

PS, hi @seesemichaelj, hope all is well!

**Comment by mikeseese** [comment]
Hi @MicaiahReid! All is well; programming a game alone is lonely, but I'm enjoying it! Hope all is well with the family and that you're enjoying Truffle!
