### ISSUE TITLE
accounts being created when specified zero

### ISSUE THREAD

**Issue by Code0x2** [ConsenSys-archive/ganache#906]
## Expected Behavior

Creating a provider with options `{fork:'http://',accounts:0}` should start a new fork with zero accounts being generated 

## Current Behavior

The fork instance has 10 accounts anyway. When using a number other than 0 in the accounts parameter, it returns the following error: `UnhandledPromiseRejectionWarning: TypeError: t.options.accounts.map is not a function`. Using the `a` shortcut parameter causes it to be ignored. 

## Steps to Reproduce (for bugs)

demo of zero account error: https://replit.com/@code0x2/ganache-test#index.js

1.Create new ganache provider instance with option accounts:0
2.Call eth_getAccounts on the provider

## Context

Creating new instances it uses 10 extra calls. Not a big problem but sucks when using infura and creating a lot of instances 

## Your Environment
* Version used:6.12.2
* Version of Truffle/Remix/Other tools used: web3 1.3
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x, [x] 14.x
* Operating System and version (include distro if Linux): windows 10
* I intend to submit a pull request to fix this issue: [ ]

**Comment by davidmurdoch** [comment]
Fix for this is in progress here: https://github.com/trufflesuite/ganache-core/pull/817 and will be tracked by https://github.com/trufflesuite/ganache-core/issues/60 Thanks!

**Comment by Code0x2** [comment]
> 
> 
> Fix for this is in progress here: #817 and will be tracked by #60 Thanks!

note setting a fixed number doesnt work either. 👍

**Comment by cds-amal** [comment]
Hi @Code0x2, 

Not sure what you mean by `a fixed number doesn't work`, can you be a little more specific? Thanks.

**Comment by Code0x2** [comment]
> 
> 
> Hi @Code0x2,
> 
> Not sure what you mean by `a fixed number doesn't work`, can you be a little more specific? Thanks.

Sorry bout that I mean if you set it to any number that isnt zero on `accounts` param it shows `t.options.accounts.map is not a function`

**Comment by davidmurdoch** [comment]
Ah, that's because the option is `total_accounts`, not `accounts`. Let me know if changing that fixes it for you!

**Comment by gnidan** [comment]
Closing this for issue maintenance. Hopefully this fixes the problem for you! Let us know if it doesn't. Thanks!
