### ISSUE TITLE
Support london hardfork

### ISSUE THREAD

**Issue by KaiRo-at** [ConsenSys-archive/ganache#939]
This is basically the same as  trufflesuite/ganache-cli#821 just for London, which is already deployed on Ropsten and Goerli and coming to Ethereum mainnet in early August.

## Expected Behavior

`ganache-cli --hardfork london` should work and behave like other Ethereum nodes running on London hardfork.

## Current Behavior

`Error: Hardfork with name london not supported`

## Possible Solution

I guess the solution is obvious, the EIPs in https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/london.md need to be implemented and followed when that hardfork setting is there. Most importantly, that means support of EIP-1559 transactions.

## Context

As with trufflesuite/ganache-cli#821, running ganache should be good in finding out gas requirements on real networks, which due to more changes in this hardfork compared to Berlin, is even more wrong for networks that are already on London.

That said, as a testing environment, it would be even more important to be able to run tests with EIP-1559 transaction semantics to get them right in various code that should run against a real network. Right now, that's now possible with using ganache.

## Your Environment
* Version used: `Ganache CLI v6.12.2 (ganache-core: 2.13.2)`
* NodeJS Version: `v10.24.0`
* Operating System and version (include distro if Linux): openSUSE Linux

**Comment by MatthiasLohr** [comment]
Should that already be available via Docker image `trufflesuite/ganache:v7.0.0-beta.0`? I can run a container using this image with `--hardfork london`, so I assue it to be supported there, but I'm getting the following message with web3py:

```The method eth_maxPriorityFeePerGas does not exist/is not available```

Any idea? Running the same code against geth with london support, it works.

**Comment by davidmurdoch** [comment]
@MatthiasLohr, I've created [an issue](https://github.com/trufflesuite/ganache/issues/1632) to add support for this method. I think we'll just need to return a hardcoded `0x0`. Some further investigation is needed here.
