### ISSUE TITLE
Fails if FROM address is 0x0

### ISSUE THREAD

**Issue by aelmanaa** [ConsenSys-archive/ganache#948]
Hi,

I'm running a local blockchain on my computer using ganache-cli  (which was installed via npm).   I was testing a chainlink node to communicate with a smartcontract, during my tests, my ganache fails with the following error

` UnhandledPromiseRejectionWarning: Error: The nonce generation function failed, or the private key was invalid`

which is triggered by 

`at Object.ecdsaSign (/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:21465)`

while investigating, I noticed that the chainlink node uses a 0x0 FROM address to call a function

```
eth_call
   > {
   >   "jsonrpc": "2.0",
   >   "id": 5,
   >   "method": "eth_call",
   >   "params": [
   >     {
   >       "from": "0x0000000000000000000000000000000000000000",
   >       "data": "0xfeaf968c",
   >       "to": "0xf1fe0a26ad90e535ad190a527502c6c39f08b1de"
   >     },
   >     "latest"
   >   ]
   > }
```

If I run the same test with any public blockchain (kovan or rinkeby) , it works fine.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

It's not a transaction. It is a simple call to retrieve a state value. Hence the value of the FROM address doesn't matter. Moreover, it works fine on Rinkeby or Kovan so it should work fine on Ganache-cli as well

## Current Behavior

ganache-cli fails 

```
(node:69055) UnhandledPromiseRejectionWarning: Error: The nonce generation function failed, or the private key was invalid

(node:69055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 40)
(node:69055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce (for bugs)

call an external view function from a truffle script. Just setup "FROM" address as 0x0

`<any_external_view_function>.call({ from: "0x0000000000000000000000000000000000000000" })`

## Context

I'm trying to run the  [Chainlink decentralized model](https://docs.chain.link/docs/architecture-decentralized-model/) locally before deploying on testnets. The Oracle node (which sets the FROM address) is a software written in golang (Hence, cannot modify the source code). 

## Your Environment
* Version used: v6.12.2
* Version of Truffle: v5.3.14
* NodeJS Version:  v12.22.1
* Operating System and version (include distro if Linux): MacOs

**Comment by jeffywu** [comment]
@davidmurdoch I'm fairly certain that this issue does not have to do with 0x0 addresses but rather usage of the `unlock` parameter for some accounts. I ran into this issue after having deployed contracts using `unlock` to get a consistent address and then snapshotting the environment into a docker container.

I was using 0x0 addresses during `call` operations before and did not encounter this issue. I only began seeing in when I started to use `unlock`.

Using unlock within one environment seems to work fine but when that chaindb is loaded into a docker container and started it causes these UnhandledPromiseRejections. Even ensuring that the second Dockerfile has the proper address unlocked does not seem to resolve the issue. The error also seems to throw even if you never use the unlocked account again.

Here's an example of the Dockerfile:
```
FROM trufflesuite/ganache-cli:latest

ADD chaindb /tmp/chaindb

ENV NODE_OPTIONS "--max-old-space-size=16000"

ENTRYPOINT [ "node", \
             "/app/ganache-core.docker.cli.js", \
             "--db", "/tmp/chaindb", \
             "--networkId", "1337", \
             "--unlock", "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", \
             "--mnemonic", "owner dignity sense" ]
```

**Comment by davidmurdoch** [comment]
Thanks @aelmanaa for opening this issue, and to @jeffywu for the additional details! Can you try with the [new `ganache@alpha` package](https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.0)? Note: there isn't a published Docker container for this release yet.

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if there's still a problem here and we can take another look.  Thanks!

**Comment by adjisb** [comment]
Hi, I'm unlocking this address: 0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE on a mumbai fork to try to emulate polygon system account.
When I send the following transaction I get in the ganache v7.0.0 container log I get the same error "The nonce generation function failed, or the private key was invalid": 
`
mumbai_1   |    >  eth_sendTransaction: [
mumbai_1   |    >   {
mumbai_1   |    >     "gas": "0xcd3f",
mumbai_1   |    >     "from": "0xfffffffffffffffffffffffffffffffffffffffe",
mumbai_1   |    >     "to": "0x0000000000000000000000000000000000001001",
mumbai_1   |    >     "data": "0x19494a1700000000000000000000000000000000000000000000000000000000622b50e70000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000011ef9011b82812a94b5505a6d998549090530911180f38ac5130101c6b9010087a7811f4bfedea3d341ad165680ae306b01aaeacc205d227629cf157dd9f821000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000005f890c9522dce5670d741d4277bfcc2d9ca8af02000000000000000000000000b5505a6d998549090530911180f38ac5130101c600000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001d97c0000"
`

Any idea ?

**Comment by davidmurdoch** [comment]
@adjisb can you open a new issue?

**Comment by adjisb** [comment]
Sure: https://github.com/trufflesuite/ganache/issues/2586
