### ISSUE TITLE
Runtime revert issue in ganache.

### ISSUE THREAD

**Issue by racetrack0616** [ConsenSys-archive/ganache#954]
My code is
  ```
uint256 length = values.length;
        for (uint256 i = 0; i < length; i++) {
            props[_sn][values[i]].push(propID);
        }
```
It is always giving me following error as in screenshot enter image description here

![image](https://user-images.githubusercontent.com/68948218/120276361-4e72d000-c2d2-11eb-97af-0d32c8ebbbcb.png)
I did some experiments with the code block like below and its is working. I only placed static value in second index of props array.i.e replaced values[i] with 0 and it really worked.
```

uint256 length = values.length;
        for (uint256 i = 0; i < length; i++) {
            props[_sn][0].push(propID);
        }
```
What is wrong with the code? Can anyone guide me?

**Comment by davidmurdoch** [comment]
Not sure what's happening here with the limited code you've provided, but my hunch is that `props[_sn][values[i]]` is out of range at some point; `values.length` and `props.length` are probably not equal.

**Comment by haltman-at** [comment]
Closing this for issue maintenance.
