### ISSUE TITLE
 'Runtime Error: revert' - when creating contract from contract

### ISSUE THREAD

**Issue by tapmapp** [ConsenSys-archive/ganache#958]
Hello, I have this basic contracts in solidity but when i try to create a contract from another contract I have this 'Runtime Error: revert'

// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.6.0 <0.9.0;

contract User {

  string public name;

  constructor(string memory _name) public payable {
    name = _name;
  }

  function getUserName() public view returns(string memory _name) {
    return name;
  }

}

contract Users {

  User[] public users;
  User public user;

  function create(string memory _name) public {
    User user = new User(_name);
  }

  function getUsers() public view returns (User[] memory _users) {
    return users;
  }

  function getUser() public view returns (User _user) {
    return user;
  }

}

**Comment by davidmurdoch** [comment]
Closing as it seems the original issue has been resolved. Please comment below if you are still having issues.
