### ISSUE TITLE
Can i use a full node data to fork a new chain using ganache-cli

### ISSUE THREAD

**Issue by moda20** [ConsenSys-archive/ganache#974]
## Context

I am trying to use the forking feature of ganache-cli to get a dry-run version of an EVM-compatible blockchain. my issue is that after a while of running `ganache-cli` with the `--fork` option, all transactions start to timeout as, in my opinion, ganache loses contact with the original blockchain RPC endpoint that I used when launching. this is a major issue I am facing and my only reasonable fix is to download or synchronize a node locally and use the chain data from that node as a basis for my new ganache-based test system, of course with the added accounts.

Is there a way to do that, i can't seem to find how to do that in the official docs or here on github.

## Your Environment
* Version used:  v6.12.2 (ganache-core: 2.13.2)
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: 14.x
* Operating System and version (include distro if Linux): linux ubuntu

**Comment by kevinbluer** [comment]
Hey @moda20! Technically yes, although there are some known issues with Ganache 6.x...would you be ok to try this with [ganache@7.0.0-alpha.0](https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.0)? It's also worth noting that sometimes a full node is insufficient (vs an archive node)...if you're curious about the differences in node types, there's a good breakdown on ethereum.org [here](https://ethereum.org/en/developers/docs/nodes-and-clients/).

Let us know how you get on 👍

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if there's still a problem here.  Thanks!
